package org.apache.spark.sql.catalyst.util

object DateTimeConstants {
  val YEARS_PER_DECADE = 10
  val YEARS_PER_CENTURY = 100
  val YEARS_PER_MILLENNIUM = 1000
  val MONTHS_PER_QUARTER = 3
  val MONTHS_PER_YEAR = 12
  val DAYS_PER_WEEK = 7
  val DAYS_PER_MONTH = 30L
  val HOURS_PER_DAY = 24L
  val MINUTES_PER_HOUR = 60L
  val SECONDS_PER_MINUTE = 60L
  val SECONDS_PER_HOUR: Long = MINUTES_PER_HOUR * SECONDS_PER_MINUTE
  val SECONDS_PER_DAY: Long = HOURS_PER_DAY * SECONDS_PER_HOUR
  val MILLIS_PER_SECOND = 1000L
  val MILLIS_PER_MINUTE: Long = SECONDS_PER_MINUTE * MILLIS_PER_SECOND
  val MILLIS_PER_HOUR: Long = MINUTES_PER_HOUR * MILLIS_PER_MINUTE
  val MILLIS_PER_DAY: Long = HOURS_PER_DAY * MILLIS_PER_HOUR
  val MICROS_PER_MILLIS = 1000L
  val MICROS_PER_SECOND: Long = MILLIS_PER_SECOND * MICROS_PER_MILLIS
  val MICROS_PER_MINUTE: Long = SECONDS_PER_MINUTE * MICROS_PER_SECOND
  val MICROS_PER_HOUR: Long = MINUTES_PER_HOUR * MICROS_PER_MINUTE
  val MICROS_PER_DAY: Long = HOURS_PER_DAY * MICROS_PER_HOUR
  val MICROS_PER_MONTH: Long = DAYS_PER_MONTH * MICROS_PER_DAY
  /* 365.25 days per year assumes leap year every four years */ val MICROS_PER_YEAR: Long = (36525L * MICROS_PER_DAY) / 100
  val NANOS_PER_MICROS = 1000L
  val NANOS_PER_MILLIS: Long = MICROS_PER_MILLIS * NANOS_PER_MICROS
  val NANOS_PER_SECOND: Long = MILLIS_PER_SECOND * NANOS_PER_MILLIS
}

