// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: master_base.proto

package moonbox.protocol.protobuf;

public interface AccessRequestPBOrBuilder extends
    // @@protoc_insertion_point(interface_extends:moonbox.AccessRequestPB)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string app_type = 3;</code>
   */
  java.lang.String getAppType();
  /**
   * <code>string app_type = 3;</code>
   */
  com.google.protobuf.ByteString
      getAppTypeBytes();

  /**
   * <code>string app_name = 4;</code>
   */
  java.lang.String getAppName();
  /**
   * <code>string app_name = 4;</code>
   */
  com.google.protobuf.ByteString
      getAppNameBytes();
}
