// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app_base.proto

package moonbox.protocol.protobuf;

/**
 * Protobuf type {@code moonbox.AppRequestMessage}
 */
public  final class AppRequestMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:moonbox.AppRequestMessage)
    AppRequestMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AppRequestMessage.newBuilder() to construct.
  private AppRequestMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AppRequestMessage() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AppRequestMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            moonbox.protocol.protobuf.OpenSessionRequestPB.Builder subBuilder = null;
            if (messageCase_ == 1) {
              subBuilder = ((moonbox.protocol.protobuf.OpenSessionRequestPB) message_).toBuilder();
            }
            message_ =
                input.readMessage(moonbox.protocol.protobuf.OpenSessionRequestPB.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((moonbox.protocol.protobuf.OpenSessionRequestPB) message_);
              message_ = subBuilder.buildPartial();
            }
            messageCase_ = 1;
            break;
          }
          case 18: {
            moonbox.protocol.protobuf.CloseSessionRequestPB.Builder subBuilder = null;
            if (messageCase_ == 2) {
              subBuilder = ((moonbox.protocol.protobuf.CloseSessionRequestPB) message_).toBuilder();
            }
            message_ =
                input.readMessage(moonbox.protocol.protobuf.CloseSessionRequestPB.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((moonbox.protocol.protobuf.CloseSessionRequestPB) message_);
              message_ = subBuilder.buildPartial();
            }
            messageCase_ = 2;
            break;
          }
          case 26: {
            moonbox.protocol.protobuf.ExecutionRequestPB.Builder subBuilder = null;
            if (messageCase_ == 3) {
              subBuilder = ((moonbox.protocol.protobuf.ExecutionRequestPB) message_).toBuilder();
            }
            message_ =
                input.readMessage(moonbox.protocol.protobuf.ExecutionRequestPB.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((moonbox.protocol.protobuf.ExecutionRequestPB) message_);
              message_ = subBuilder.buildPartial();
            }
            messageCase_ = 3;
            break;
          }
          case 34: {
            moonbox.protocol.protobuf.ExecutionResultRequestPB.Builder subBuilder = null;
            if (messageCase_ == 4) {
              subBuilder = ((moonbox.protocol.protobuf.ExecutionResultRequestPB) message_).toBuilder();
            }
            message_ =
                input.readMessage(moonbox.protocol.protobuf.ExecutionResultRequestPB.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((moonbox.protocol.protobuf.ExecutionResultRequestPB) message_);
              message_ = subBuilder.buildPartial();
            }
            messageCase_ = 4;
            break;
          }
          case 42: {
            moonbox.protocol.protobuf.ExecutionCancelRequestPB.Builder subBuilder = null;
            if (messageCase_ == 5) {
              subBuilder = ((moonbox.protocol.protobuf.ExecutionCancelRequestPB) message_).toBuilder();
            }
            message_ =
                input.readMessage(moonbox.protocol.protobuf.ExecutionCancelRequestPB.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((moonbox.protocol.protobuf.ExecutionCancelRequestPB) message_);
              message_ = subBuilder.buildPartial();
            }
            messageCase_ = 5;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return moonbox.protocol.protobuf.AppBase.internal_static_moonbox_AppRequestMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return moonbox.protocol.protobuf.AppBase.internal_static_moonbox_AppRequestMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            moonbox.protocol.protobuf.AppRequestMessage.class, moonbox.protocol.protobuf.AppRequestMessage.Builder.class);
  }

  private int messageCase_ = 0;
  private java.lang.Object message_;
  public enum MessageCase
      implements com.google.protobuf.Internal.EnumLite {
    OPEN_SESSION(1),
    CLOSE_SESSION(2),
    EXECUTE(3),
    EXECUTE_RESULT(4),
    EXECTE_CANCEL(5),
    MESSAGE_NOT_SET(0);
    private final int value;
    private MessageCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageCase valueOf(int value) {
      return forNumber(value);
    }

    public static MessageCase forNumber(int value) {
      switch (value) {
        case 1: return OPEN_SESSION;
        case 2: return CLOSE_SESSION;
        case 3: return EXECUTE;
        case 4: return EXECUTE_RESULT;
        case 5: return EXECTE_CANCEL;
        case 0: return MESSAGE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public MessageCase
  getMessageCase() {
    return MessageCase.forNumber(
        messageCase_);
  }

  public static final int OPEN_SESSION_FIELD_NUMBER = 1;
  /**
   * <code>.moonbox.OpenSessionRequestPB open_session = 1;</code>
   */
  public boolean hasOpenSession() {
    return messageCase_ == 1;
  }
  /**
   * <code>.moonbox.OpenSessionRequestPB open_session = 1;</code>
   */
  public moonbox.protocol.protobuf.OpenSessionRequestPB getOpenSession() {
    if (messageCase_ == 1) {
       return (moonbox.protocol.protobuf.OpenSessionRequestPB) message_;
    }
    return moonbox.protocol.protobuf.OpenSessionRequestPB.getDefaultInstance();
  }
  /**
   * <code>.moonbox.OpenSessionRequestPB open_session = 1;</code>
   */
  public moonbox.protocol.protobuf.OpenSessionRequestPBOrBuilder getOpenSessionOrBuilder() {
    if (messageCase_ == 1) {
       return (moonbox.protocol.protobuf.OpenSessionRequestPB) message_;
    }
    return moonbox.protocol.protobuf.OpenSessionRequestPB.getDefaultInstance();
  }

  public static final int CLOSE_SESSION_FIELD_NUMBER = 2;
  /**
   * <code>.moonbox.CloseSessionRequestPB close_session = 2;</code>
   */
  public boolean hasCloseSession() {
    return messageCase_ == 2;
  }
  /**
   * <code>.moonbox.CloseSessionRequestPB close_session = 2;</code>
   */
  public moonbox.protocol.protobuf.CloseSessionRequestPB getCloseSession() {
    if (messageCase_ == 2) {
       return (moonbox.protocol.protobuf.CloseSessionRequestPB) message_;
    }
    return moonbox.protocol.protobuf.CloseSessionRequestPB.getDefaultInstance();
  }
  /**
   * <code>.moonbox.CloseSessionRequestPB close_session = 2;</code>
   */
  public moonbox.protocol.protobuf.CloseSessionRequestPBOrBuilder getCloseSessionOrBuilder() {
    if (messageCase_ == 2) {
       return (moonbox.protocol.protobuf.CloseSessionRequestPB) message_;
    }
    return moonbox.protocol.protobuf.CloseSessionRequestPB.getDefaultInstance();
  }

  public static final int EXECUTE_FIELD_NUMBER = 3;
  /**
   * <code>.moonbox.ExecutionRequestPB execute = 3;</code>
   */
  public boolean hasExecute() {
    return messageCase_ == 3;
  }
  /**
   * <code>.moonbox.ExecutionRequestPB execute = 3;</code>
   */
  public moonbox.protocol.protobuf.ExecutionRequestPB getExecute() {
    if (messageCase_ == 3) {
       return (moonbox.protocol.protobuf.ExecutionRequestPB) message_;
    }
    return moonbox.protocol.protobuf.ExecutionRequestPB.getDefaultInstance();
  }
  /**
   * <code>.moonbox.ExecutionRequestPB execute = 3;</code>
   */
  public moonbox.protocol.protobuf.ExecutionRequestPBOrBuilder getExecuteOrBuilder() {
    if (messageCase_ == 3) {
       return (moonbox.protocol.protobuf.ExecutionRequestPB) message_;
    }
    return moonbox.protocol.protobuf.ExecutionRequestPB.getDefaultInstance();
  }

  public static final int EXECUTE_RESULT_FIELD_NUMBER = 4;
  /**
   * <code>.moonbox.ExecutionResultRequestPB execute_result = 4;</code>
   */
  public boolean hasExecuteResult() {
    return messageCase_ == 4;
  }
  /**
   * <code>.moonbox.ExecutionResultRequestPB execute_result = 4;</code>
   */
  public moonbox.protocol.protobuf.ExecutionResultRequestPB getExecuteResult() {
    if (messageCase_ == 4) {
       return (moonbox.protocol.protobuf.ExecutionResultRequestPB) message_;
    }
    return moonbox.protocol.protobuf.ExecutionResultRequestPB.getDefaultInstance();
  }
  /**
   * <code>.moonbox.ExecutionResultRequestPB execute_result = 4;</code>
   */
  public moonbox.protocol.protobuf.ExecutionResultRequestPBOrBuilder getExecuteResultOrBuilder() {
    if (messageCase_ == 4) {
       return (moonbox.protocol.protobuf.ExecutionResultRequestPB) message_;
    }
    return moonbox.protocol.protobuf.ExecutionResultRequestPB.getDefaultInstance();
  }

  public static final int EXECTE_CANCEL_FIELD_NUMBER = 5;
  /**
   * <code>.moonbox.ExecutionCancelRequestPB execte_cancel = 5;</code>
   */
  public boolean hasExecteCancel() {
    return messageCase_ == 5;
  }
  /**
   * <code>.moonbox.ExecutionCancelRequestPB execte_cancel = 5;</code>
   */
  public moonbox.protocol.protobuf.ExecutionCancelRequestPB getExecteCancel() {
    if (messageCase_ == 5) {
       return (moonbox.protocol.protobuf.ExecutionCancelRequestPB) message_;
    }
    return moonbox.protocol.protobuf.ExecutionCancelRequestPB.getDefaultInstance();
  }
  /**
   * <code>.moonbox.ExecutionCancelRequestPB execte_cancel = 5;</code>
   */
  public moonbox.protocol.protobuf.ExecutionCancelRequestPBOrBuilder getExecteCancelOrBuilder() {
    if (messageCase_ == 5) {
       return (moonbox.protocol.protobuf.ExecutionCancelRequestPB) message_;
    }
    return moonbox.protocol.protobuf.ExecutionCancelRequestPB.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (messageCase_ == 1) {
      output.writeMessage(1, (moonbox.protocol.protobuf.OpenSessionRequestPB) message_);
    }
    if (messageCase_ == 2) {
      output.writeMessage(2, (moonbox.protocol.protobuf.CloseSessionRequestPB) message_);
    }
    if (messageCase_ == 3) {
      output.writeMessage(3, (moonbox.protocol.protobuf.ExecutionRequestPB) message_);
    }
    if (messageCase_ == 4) {
      output.writeMessage(4, (moonbox.protocol.protobuf.ExecutionResultRequestPB) message_);
    }
    if (messageCase_ == 5) {
      output.writeMessage(5, (moonbox.protocol.protobuf.ExecutionCancelRequestPB) message_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (messageCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (moonbox.protocol.protobuf.OpenSessionRequestPB) message_);
    }
    if (messageCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (moonbox.protocol.protobuf.CloseSessionRequestPB) message_);
    }
    if (messageCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (moonbox.protocol.protobuf.ExecutionRequestPB) message_);
    }
    if (messageCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (moonbox.protocol.protobuf.ExecutionResultRequestPB) message_);
    }
    if (messageCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (moonbox.protocol.protobuf.ExecutionCancelRequestPB) message_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof moonbox.protocol.protobuf.AppRequestMessage)) {
      return super.equals(obj);
    }
    moonbox.protocol.protobuf.AppRequestMessage other = (moonbox.protocol.protobuf.AppRequestMessage) obj;

    boolean result = true;
    result = result && getMessageCase().equals(
        other.getMessageCase());
    if (!result) return false;
    switch (messageCase_) {
      case 1:
        result = result && getOpenSession()
            .equals(other.getOpenSession());
        break;
      case 2:
        result = result && getCloseSession()
            .equals(other.getCloseSession());
        break;
      case 3:
        result = result && getExecute()
            .equals(other.getExecute());
        break;
      case 4:
        result = result && getExecuteResult()
            .equals(other.getExecuteResult());
        break;
      case 5:
        result = result && getExecteCancel()
            .equals(other.getExecteCancel());
        break;
      case 0:
      default:
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (messageCase_) {
      case 1:
        hash = (37 * hash) + OPEN_SESSION_FIELD_NUMBER;
        hash = (53 * hash) + getOpenSession().hashCode();
        break;
      case 2:
        hash = (37 * hash) + CLOSE_SESSION_FIELD_NUMBER;
        hash = (53 * hash) + getCloseSession().hashCode();
        break;
      case 3:
        hash = (37 * hash) + EXECUTE_FIELD_NUMBER;
        hash = (53 * hash) + getExecute().hashCode();
        break;
      case 4:
        hash = (37 * hash) + EXECUTE_RESULT_FIELD_NUMBER;
        hash = (53 * hash) + getExecuteResult().hashCode();
        break;
      case 5:
        hash = (37 * hash) + EXECTE_CANCEL_FIELD_NUMBER;
        hash = (53 * hash) + getExecteCancel().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static moonbox.protocol.protobuf.AppRequestMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static moonbox.protocol.protobuf.AppRequestMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static moonbox.protocol.protobuf.AppRequestMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static moonbox.protocol.protobuf.AppRequestMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static moonbox.protocol.protobuf.AppRequestMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static moonbox.protocol.protobuf.AppRequestMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static moonbox.protocol.protobuf.AppRequestMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static moonbox.protocol.protobuf.AppRequestMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static moonbox.protocol.protobuf.AppRequestMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static moonbox.protocol.protobuf.AppRequestMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static moonbox.protocol.protobuf.AppRequestMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static moonbox.protocol.protobuf.AppRequestMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(moonbox.protocol.protobuf.AppRequestMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code moonbox.AppRequestMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:moonbox.AppRequestMessage)
      moonbox.protocol.protobuf.AppRequestMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return moonbox.protocol.protobuf.AppBase.internal_static_moonbox_AppRequestMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return moonbox.protocol.protobuf.AppBase.internal_static_moonbox_AppRequestMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              moonbox.protocol.protobuf.AppRequestMessage.class, moonbox.protocol.protobuf.AppRequestMessage.Builder.class);
    }

    // Construct using moonbox.protocol.protobuf.AppRequestMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      messageCase_ = 0;
      message_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return moonbox.protocol.protobuf.AppBase.internal_static_moonbox_AppRequestMessage_descriptor;
    }

    @java.lang.Override
    public moonbox.protocol.protobuf.AppRequestMessage getDefaultInstanceForType() {
      return moonbox.protocol.protobuf.AppRequestMessage.getDefaultInstance();
    }

    @java.lang.Override
    public moonbox.protocol.protobuf.AppRequestMessage build() {
      moonbox.protocol.protobuf.AppRequestMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public moonbox.protocol.protobuf.AppRequestMessage buildPartial() {
      moonbox.protocol.protobuf.AppRequestMessage result = new moonbox.protocol.protobuf.AppRequestMessage(this);
      if (messageCase_ == 1) {
        if (openSessionBuilder_ == null) {
          result.message_ = message_;
        } else {
          result.message_ = openSessionBuilder_.build();
        }
      }
      if (messageCase_ == 2) {
        if (closeSessionBuilder_ == null) {
          result.message_ = message_;
        } else {
          result.message_ = closeSessionBuilder_.build();
        }
      }
      if (messageCase_ == 3) {
        if (executeBuilder_ == null) {
          result.message_ = message_;
        } else {
          result.message_ = executeBuilder_.build();
        }
      }
      if (messageCase_ == 4) {
        if (executeResultBuilder_ == null) {
          result.message_ = message_;
        } else {
          result.message_ = executeResultBuilder_.build();
        }
      }
      if (messageCase_ == 5) {
        if (execteCancelBuilder_ == null) {
          result.message_ = message_;
        } else {
          result.message_ = execteCancelBuilder_.build();
        }
      }
      result.messageCase_ = messageCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof moonbox.protocol.protobuf.AppRequestMessage) {
        return mergeFrom((moonbox.protocol.protobuf.AppRequestMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(moonbox.protocol.protobuf.AppRequestMessage other) {
      if (other == moonbox.protocol.protobuf.AppRequestMessage.getDefaultInstance()) return this;
      switch (other.getMessageCase()) {
        case OPEN_SESSION: {
          mergeOpenSession(other.getOpenSession());
          break;
        }
        case CLOSE_SESSION: {
          mergeCloseSession(other.getCloseSession());
          break;
        }
        case EXECUTE: {
          mergeExecute(other.getExecute());
          break;
        }
        case EXECUTE_RESULT: {
          mergeExecuteResult(other.getExecuteResult());
          break;
        }
        case EXECTE_CANCEL: {
          mergeExecteCancel(other.getExecteCancel());
          break;
        }
        case MESSAGE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      moonbox.protocol.protobuf.AppRequestMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (moonbox.protocol.protobuf.AppRequestMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int messageCase_ = 0;
    private java.lang.Object message_;
    public MessageCase
        getMessageCase() {
      return MessageCase.forNumber(
          messageCase_);
    }

    public Builder clearMessage() {
      messageCase_ = 0;
      message_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        moonbox.protocol.protobuf.OpenSessionRequestPB, moonbox.protocol.protobuf.OpenSessionRequestPB.Builder, moonbox.protocol.protobuf.OpenSessionRequestPBOrBuilder> openSessionBuilder_;
    /**
     * <code>.moonbox.OpenSessionRequestPB open_session = 1;</code>
     */
    public boolean hasOpenSession() {
      return messageCase_ == 1;
    }
    /**
     * <code>.moonbox.OpenSessionRequestPB open_session = 1;</code>
     */
    public moonbox.protocol.protobuf.OpenSessionRequestPB getOpenSession() {
      if (openSessionBuilder_ == null) {
        if (messageCase_ == 1) {
          return (moonbox.protocol.protobuf.OpenSessionRequestPB) message_;
        }
        return moonbox.protocol.protobuf.OpenSessionRequestPB.getDefaultInstance();
      } else {
        if (messageCase_ == 1) {
          return openSessionBuilder_.getMessage();
        }
        return moonbox.protocol.protobuf.OpenSessionRequestPB.getDefaultInstance();
      }
    }
    /**
     * <code>.moonbox.OpenSessionRequestPB open_session = 1;</code>
     */
    public Builder setOpenSession(moonbox.protocol.protobuf.OpenSessionRequestPB value) {
      if (openSessionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        openSessionBuilder_.setMessage(value);
      }
      messageCase_ = 1;
      return this;
    }
    /**
     * <code>.moonbox.OpenSessionRequestPB open_session = 1;</code>
     */
    public Builder setOpenSession(
        moonbox.protocol.protobuf.OpenSessionRequestPB.Builder builderForValue) {
      if (openSessionBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        openSessionBuilder_.setMessage(builderForValue.build());
      }
      messageCase_ = 1;
      return this;
    }
    /**
     * <code>.moonbox.OpenSessionRequestPB open_session = 1;</code>
     */
    public Builder mergeOpenSession(moonbox.protocol.protobuf.OpenSessionRequestPB value) {
      if (openSessionBuilder_ == null) {
        if (messageCase_ == 1 &&
            message_ != moonbox.protocol.protobuf.OpenSessionRequestPB.getDefaultInstance()) {
          message_ = moonbox.protocol.protobuf.OpenSessionRequestPB.newBuilder((moonbox.protocol.protobuf.OpenSessionRequestPB) message_)
              .mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        if (messageCase_ == 1) {
          openSessionBuilder_.mergeFrom(value);
        }
        openSessionBuilder_.setMessage(value);
      }
      messageCase_ = 1;
      return this;
    }
    /**
     * <code>.moonbox.OpenSessionRequestPB open_session = 1;</code>
     */
    public Builder clearOpenSession() {
      if (openSessionBuilder_ == null) {
        if (messageCase_ == 1) {
          messageCase_ = 0;
          message_ = null;
          onChanged();
        }
      } else {
        if (messageCase_ == 1) {
          messageCase_ = 0;
          message_ = null;
        }
        openSessionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.moonbox.OpenSessionRequestPB open_session = 1;</code>
     */
    public moonbox.protocol.protobuf.OpenSessionRequestPB.Builder getOpenSessionBuilder() {
      return getOpenSessionFieldBuilder().getBuilder();
    }
    /**
     * <code>.moonbox.OpenSessionRequestPB open_session = 1;</code>
     */
    public moonbox.protocol.protobuf.OpenSessionRequestPBOrBuilder getOpenSessionOrBuilder() {
      if ((messageCase_ == 1) && (openSessionBuilder_ != null)) {
        return openSessionBuilder_.getMessageOrBuilder();
      } else {
        if (messageCase_ == 1) {
          return (moonbox.protocol.protobuf.OpenSessionRequestPB) message_;
        }
        return moonbox.protocol.protobuf.OpenSessionRequestPB.getDefaultInstance();
      }
    }
    /**
     * <code>.moonbox.OpenSessionRequestPB open_session = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        moonbox.protocol.protobuf.OpenSessionRequestPB, moonbox.protocol.protobuf.OpenSessionRequestPB.Builder, moonbox.protocol.protobuf.OpenSessionRequestPBOrBuilder> 
        getOpenSessionFieldBuilder() {
      if (openSessionBuilder_ == null) {
        if (!(messageCase_ == 1)) {
          message_ = moonbox.protocol.protobuf.OpenSessionRequestPB.getDefaultInstance();
        }
        openSessionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            moonbox.protocol.protobuf.OpenSessionRequestPB, moonbox.protocol.protobuf.OpenSessionRequestPB.Builder, moonbox.protocol.protobuf.OpenSessionRequestPBOrBuilder>(
                (moonbox.protocol.protobuf.OpenSessionRequestPB) message_,
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      messageCase_ = 1;
      onChanged();;
      return openSessionBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        moonbox.protocol.protobuf.CloseSessionRequestPB, moonbox.protocol.protobuf.CloseSessionRequestPB.Builder, moonbox.protocol.protobuf.CloseSessionRequestPBOrBuilder> closeSessionBuilder_;
    /**
     * <code>.moonbox.CloseSessionRequestPB close_session = 2;</code>
     */
    public boolean hasCloseSession() {
      return messageCase_ == 2;
    }
    /**
     * <code>.moonbox.CloseSessionRequestPB close_session = 2;</code>
     */
    public moonbox.protocol.protobuf.CloseSessionRequestPB getCloseSession() {
      if (closeSessionBuilder_ == null) {
        if (messageCase_ == 2) {
          return (moonbox.protocol.protobuf.CloseSessionRequestPB) message_;
        }
        return moonbox.protocol.protobuf.CloseSessionRequestPB.getDefaultInstance();
      } else {
        if (messageCase_ == 2) {
          return closeSessionBuilder_.getMessage();
        }
        return moonbox.protocol.protobuf.CloseSessionRequestPB.getDefaultInstance();
      }
    }
    /**
     * <code>.moonbox.CloseSessionRequestPB close_session = 2;</code>
     */
    public Builder setCloseSession(moonbox.protocol.protobuf.CloseSessionRequestPB value) {
      if (closeSessionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        closeSessionBuilder_.setMessage(value);
      }
      messageCase_ = 2;
      return this;
    }
    /**
     * <code>.moonbox.CloseSessionRequestPB close_session = 2;</code>
     */
    public Builder setCloseSession(
        moonbox.protocol.protobuf.CloseSessionRequestPB.Builder builderForValue) {
      if (closeSessionBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        closeSessionBuilder_.setMessage(builderForValue.build());
      }
      messageCase_ = 2;
      return this;
    }
    /**
     * <code>.moonbox.CloseSessionRequestPB close_session = 2;</code>
     */
    public Builder mergeCloseSession(moonbox.protocol.protobuf.CloseSessionRequestPB value) {
      if (closeSessionBuilder_ == null) {
        if (messageCase_ == 2 &&
            message_ != moonbox.protocol.protobuf.CloseSessionRequestPB.getDefaultInstance()) {
          message_ = moonbox.protocol.protobuf.CloseSessionRequestPB.newBuilder((moonbox.protocol.protobuf.CloseSessionRequestPB) message_)
              .mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        if (messageCase_ == 2) {
          closeSessionBuilder_.mergeFrom(value);
        }
        closeSessionBuilder_.setMessage(value);
      }
      messageCase_ = 2;
      return this;
    }
    /**
     * <code>.moonbox.CloseSessionRequestPB close_session = 2;</code>
     */
    public Builder clearCloseSession() {
      if (closeSessionBuilder_ == null) {
        if (messageCase_ == 2) {
          messageCase_ = 0;
          message_ = null;
          onChanged();
        }
      } else {
        if (messageCase_ == 2) {
          messageCase_ = 0;
          message_ = null;
        }
        closeSessionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.moonbox.CloseSessionRequestPB close_session = 2;</code>
     */
    public moonbox.protocol.protobuf.CloseSessionRequestPB.Builder getCloseSessionBuilder() {
      return getCloseSessionFieldBuilder().getBuilder();
    }
    /**
     * <code>.moonbox.CloseSessionRequestPB close_session = 2;</code>
     */
    public moonbox.protocol.protobuf.CloseSessionRequestPBOrBuilder getCloseSessionOrBuilder() {
      if ((messageCase_ == 2) && (closeSessionBuilder_ != null)) {
        return closeSessionBuilder_.getMessageOrBuilder();
      } else {
        if (messageCase_ == 2) {
          return (moonbox.protocol.protobuf.CloseSessionRequestPB) message_;
        }
        return moonbox.protocol.protobuf.CloseSessionRequestPB.getDefaultInstance();
      }
    }
    /**
     * <code>.moonbox.CloseSessionRequestPB close_session = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        moonbox.protocol.protobuf.CloseSessionRequestPB, moonbox.protocol.protobuf.CloseSessionRequestPB.Builder, moonbox.protocol.protobuf.CloseSessionRequestPBOrBuilder> 
        getCloseSessionFieldBuilder() {
      if (closeSessionBuilder_ == null) {
        if (!(messageCase_ == 2)) {
          message_ = moonbox.protocol.protobuf.CloseSessionRequestPB.getDefaultInstance();
        }
        closeSessionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            moonbox.protocol.protobuf.CloseSessionRequestPB, moonbox.protocol.protobuf.CloseSessionRequestPB.Builder, moonbox.protocol.protobuf.CloseSessionRequestPBOrBuilder>(
                (moonbox.protocol.protobuf.CloseSessionRequestPB) message_,
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      messageCase_ = 2;
      onChanged();;
      return closeSessionBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        moonbox.protocol.protobuf.ExecutionRequestPB, moonbox.protocol.protobuf.ExecutionRequestPB.Builder, moonbox.protocol.protobuf.ExecutionRequestPBOrBuilder> executeBuilder_;
    /**
     * <code>.moonbox.ExecutionRequestPB execute = 3;</code>
     */
    public boolean hasExecute() {
      return messageCase_ == 3;
    }
    /**
     * <code>.moonbox.ExecutionRequestPB execute = 3;</code>
     */
    public moonbox.protocol.protobuf.ExecutionRequestPB getExecute() {
      if (executeBuilder_ == null) {
        if (messageCase_ == 3) {
          return (moonbox.protocol.protobuf.ExecutionRequestPB) message_;
        }
        return moonbox.protocol.protobuf.ExecutionRequestPB.getDefaultInstance();
      } else {
        if (messageCase_ == 3) {
          return executeBuilder_.getMessage();
        }
        return moonbox.protocol.protobuf.ExecutionRequestPB.getDefaultInstance();
      }
    }
    /**
     * <code>.moonbox.ExecutionRequestPB execute = 3;</code>
     */
    public Builder setExecute(moonbox.protocol.protobuf.ExecutionRequestPB value) {
      if (executeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        executeBuilder_.setMessage(value);
      }
      messageCase_ = 3;
      return this;
    }
    /**
     * <code>.moonbox.ExecutionRequestPB execute = 3;</code>
     */
    public Builder setExecute(
        moonbox.protocol.protobuf.ExecutionRequestPB.Builder builderForValue) {
      if (executeBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        executeBuilder_.setMessage(builderForValue.build());
      }
      messageCase_ = 3;
      return this;
    }
    /**
     * <code>.moonbox.ExecutionRequestPB execute = 3;</code>
     */
    public Builder mergeExecute(moonbox.protocol.protobuf.ExecutionRequestPB value) {
      if (executeBuilder_ == null) {
        if (messageCase_ == 3 &&
            message_ != moonbox.protocol.protobuf.ExecutionRequestPB.getDefaultInstance()) {
          message_ = moonbox.protocol.protobuf.ExecutionRequestPB.newBuilder((moonbox.protocol.protobuf.ExecutionRequestPB) message_)
              .mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        if (messageCase_ == 3) {
          executeBuilder_.mergeFrom(value);
        }
        executeBuilder_.setMessage(value);
      }
      messageCase_ = 3;
      return this;
    }
    /**
     * <code>.moonbox.ExecutionRequestPB execute = 3;</code>
     */
    public Builder clearExecute() {
      if (executeBuilder_ == null) {
        if (messageCase_ == 3) {
          messageCase_ = 0;
          message_ = null;
          onChanged();
        }
      } else {
        if (messageCase_ == 3) {
          messageCase_ = 0;
          message_ = null;
        }
        executeBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.moonbox.ExecutionRequestPB execute = 3;</code>
     */
    public moonbox.protocol.protobuf.ExecutionRequestPB.Builder getExecuteBuilder() {
      return getExecuteFieldBuilder().getBuilder();
    }
    /**
     * <code>.moonbox.ExecutionRequestPB execute = 3;</code>
     */
    public moonbox.protocol.protobuf.ExecutionRequestPBOrBuilder getExecuteOrBuilder() {
      if ((messageCase_ == 3) && (executeBuilder_ != null)) {
        return executeBuilder_.getMessageOrBuilder();
      } else {
        if (messageCase_ == 3) {
          return (moonbox.protocol.protobuf.ExecutionRequestPB) message_;
        }
        return moonbox.protocol.protobuf.ExecutionRequestPB.getDefaultInstance();
      }
    }
    /**
     * <code>.moonbox.ExecutionRequestPB execute = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        moonbox.protocol.protobuf.ExecutionRequestPB, moonbox.protocol.protobuf.ExecutionRequestPB.Builder, moonbox.protocol.protobuf.ExecutionRequestPBOrBuilder> 
        getExecuteFieldBuilder() {
      if (executeBuilder_ == null) {
        if (!(messageCase_ == 3)) {
          message_ = moonbox.protocol.protobuf.ExecutionRequestPB.getDefaultInstance();
        }
        executeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            moonbox.protocol.protobuf.ExecutionRequestPB, moonbox.protocol.protobuf.ExecutionRequestPB.Builder, moonbox.protocol.protobuf.ExecutionRequestPBOrBuilder>(
                (moonbox.protocol.protobuf.ExecutionRequestPB) message_,
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      messageCase_ = 3;
      onChanged();;
      return executeBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        moonbox.protocol.protobuf.ExecutionResultRequestPB, moonbox.protocol.protobuf.ExecutionResultRequestPB.Builder, moonbox.protocol.protobuf.ExecutionResultRequestPBOrBuilder> executeResultBuilder_;
    /**
     * <code>.moonbox.ExecutionResultRequestPB execute_result = 4;</code>
     */
    public boolean hasExecuteResult() {
      return messageCase_ == 4;
    }
    /**
     * <code>.moonbox.ExecutionResultRequestPB execute_result = 4;</code>
     */
    public moonbox.protocol.protobuf.ExecutionResultRequestPB getExecuteResult() {
      if (executeResultBuilder_ == null) {
        if (messageCase_ == 4) {
          return (moonbox.protocol.protobuf.ExecutionResultRequestPB) message_;
        }
        return moonbox.protocol.protobuf.ExecutionResultRequestPB.getDefaultInstance();
      } else {
        if (messageCase_ == 4) {
          return executeResultBuilder_.getMessage();
        }
        return moonbox.protocol.protobuf.ExecutionResultRequestPB.getDefaultInstance();
      }
    }
    /**
     * <code>.moonbox.ExecutionResultRequestPB execute_result = 4;</code>
     */
    public Builder setExecuteResult(moonbox.protocol.protobuf.ExecutionResultRequestPB value) {
      if (executeResultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        executeResultBuilder_.setMessage(value);
      }
      messageCase_ = 4;
      return this;
    }
    /**
     * <code>.moonbox.ExecutionResultRequestPB execute_result = 4;</code>
     */
    public Builder setExecuteResult(
        moonbox.protocol.protobuf.ExecutionResultRequestPB.Builder builderForValue) {
      if (executeResultBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        executeResultBuilder_.setMessage(builderForValue.build());
      }
      messageCase_ = 4;
      return this;
    }
    /**
     * <code>.moonbox.ExecutionResultRequestPB execute_result = 4;</code>
     */
    public Builder mergeExecuteResult(moonbox.protocol.protobuf.ExecutionResultRequestPB value) {
      if (executeResultBuilder_ == null) {
        if (messageCase_ == 4 &&
            message_ != moonbox.protocol.protobuf.ExecutionResultRequestPB.getDefaultInstance()) {
          message_ = moonbox.protocol.protobuf.ExecutionResultRequestPB.newBuilder((moonbox.protocol.protobuf.ExecutionResultRequestPB) message_)
              .mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        if (messageCase_ == 4) {
          executeResultBuilder_.mergeFrom(value);
        }
        executeResultBuilder_.setMessage(value);
      }
      messageCase_ = 4;
      return this;
    }
    /**
     * <code>.moonbox.ExecutionResultRequestPB execute_result = 4;</code>
     */
    public Builder clearExecuteResult() {
      if (executeResultBuilder_ == null) {
        if (messageCase_ == 4) {
          messageCase_ = 0;
          message_ = null;
          onChanged();
        }
      } else {
        if (messageCase_ == 4) {
          messageCase_ = 0;
          message_ = null;
        }
        executeResultBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.moonbox.ExecutionResultRequestPB execute_result = 4;</code>
     */
    public moonbox.protocol.protobuf.ExecutionResultRequestPB.Builder getExecuteResultBuilder() {
      return getExecuteResultFieldBuilder().getBuilder();
    }
    /**
     * <code>.moonbox.ExecutionResultRequestPB execute_result = 4;</code>
     */
    public moonbox.protocol.protobuf.ExecutionResultRequestPBOrBuilder getExecuteResultOrBuilder() {
      if ((messageCase_ == 4) && (executeResultBuilder_ != null)) {
        return executeResultBuilder_.getMessageOrBuilder();
      } else {
        if (messageCase_ == 4) {
          return (moonbox.protocol.protobuf.ExecutionResultRequestPB) message_;
        }
        return moonbox.protocol.protobuf.ExecutionResultRequestPB.getDefaultInstance();
      }
    }
    /**
     * <code>.moonbox.ExecutionResultRequestPB execute_result = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        moonbox.protocol.protobuf.ExecutionResultRequestPB, moonbox.protocol.protobuf.ExecutionResultRequestPB.Builder, moonbox.protocol.protobuf.ExecutionResultRequestPBOrBuilder> 
        getExecuteResultFieldBuilder() {
      if (executeResultBuilder_ == null) {
        if (!(messageCase_ == 4)) {
          message_ = moonbox.protocol.protobuf.ExecutionResultRequestPB.getDefaultInstance();
        }
        executeResultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            moonbox.protocol.protobuf.ExecutionResultRequestPB, moonbox.protocol.protobuf.ExecutionResultRequestPB.Builder, moonbox.protocol.protobuf.ExecutionResultRequestPBOrBuilder>(
                (moonbox.protocol.protobuf.ExecutionResultRequestPB) message_,
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      messageCase_ = 4;
      onChanged();;
      return executeResultBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        moonbox.protocol.protobuf.ExecutionCancelRequestPB, moonbox.protocol.protobuf.ExecutionCancelRequestPB.Builder, moonbox.protocol.protobuf.ExecutionCancelRequestPBOrBuilder> execteCancelBuilder_;
    /**
     * <code>.moonbox.ExecutionCancelRequestPB execte_cancel = 5;</code>
     */
    public boolean hasExecteCancel() {
      return messageCase_ == 5;
    }
    /**
     * <code>.moonbox.ExecutionCancelRequestPB execte_cancel = 5;</code>
     */
    public moonbox.protocol.protobuf.ExecutionCancelRequestPB getExecteCancel() {
      if (execteCancelBuilder_ == null) {
        if (messageCase_ == 5) {
          return (moonbox.protocol.protobuf.ExecutionCancelRequestPB) message_;
        }
        return moonbox.protocol.protobuf.ExecutionCancelRequestPB.getDefaultInstance();
      } else {
        if (messageCase_ == 5) {
          return execteCancelBuilder_.getMessage();
        }
        return moonbox.protocol.protobuf.ExecutionCancelRequestPB.getDefaultInstance();
      }
    }
    /**
     * <code>.moonbox.ExecutionCancelRequestPB execte_cancel = 5;</code>
     */
    public Builder setExecteCancel(moonbox.protocol.protobuf.ExecutionCancelRequestPB value) {
      if (execteCancelBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        execteCancelBuilder_.setMessage(value);
      }
      messageCase_ = 5;
      return this;
    }
    /**
     * <code>.moonbox.ExecutionCancelRequestPB execte_cancel = 5;</code>
     */
    public Builder setExecteCancel(
        moonbox.protocol.protobuf.ExecutionCancelRequestPB.Builder builderForValue) {
      if (execteCancelBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        execteCancelBuilder_.setMessage(builderForValue.build());
      }
      messageCase_ = 5;
      return this;
    }
    /**
     * <code>.moonbox.ExecutionCancelRequestPB execte_cancel = 5;</code>
     */
    public Builder mergeExecteCancel(moonbox.protocol.protobuf.ExecutionCancelRequestPB value) {
      if (execteCancelBuilder_ == null) {
        if (messageCase_ == 5 &&
            message_ != moonbox.protocol.protobuf.ExecutionCancelRequestPB.getDefaultInstance()) {
          message_ = moonbox.protocol.protobuf.ExecutionCancelRequestPB.newBuilder((moonbox.protocol.protobuf.ExecutionCancelRequestPB) message_)
              .mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        if (messageCase_ == 5) {
          execteCancelBuilder_.mergeFrom(value);
        }
        execteCancelBuilder_.setMessage(value);
      }
      messageCase_ = 5;
      return this;
    }
    /**
     * <code>.moonbox.ExecutionCancelRequestPB execte_cancel = 5;</code>
     */
    public Builder clearExecteCancel() {
      if (execteCancelBuilder_ == null) {
        if (messageCase_ == 5) {
          messageCase_ = 0;
          message_ = null;
          onChanged();
        }
      } else {
        if (messageCase_ == 5) {
          messageCase_ = 0;
          message_ = null;
        }
        execteCancelBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.moonbox.ExecutionCancelRequestPB execte_cancel = 5;</code>
     */
    public moonbox.protocol.protobuf.ExecutionCancelRequestPB.Builder getExecteCancelBuilder() {
      return getExecteCancelFieldBuilder().getBuilder();
    }
    /**
     * <code>.moonbox.ExecutionCancelRequestPB execte_cancel = 5;</code>
     */
    public moonbox.protocol.protobuf.ExecutionCancelRequestPBOrBuilder getExecteCancelOrBuilder() {
      if ((messageCase_ == 5) && (execteCancelBuilder_ != null)) {
        return execteCancelBuilder_.getMessageOrBuilder();
      } else {
        if (messageCase_ == 5) {
          return (moonbox.protocol.protobuf.ExecutionCancelRequestPB) message_;
        }
        return moonbox.protocol.protobuf.ExecutionCancelRequestPB.getDefaultInstance();
      }
    }
    /**
     * <code>.moonbox.ExecutionCancelRequestPB execte_cancel = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        moonbox.protocol.protobuf.ExecutionCancelRequestPB, moonbox.protocol.protobuf.ExecutionCancelRequestPB.Builder, moonbox.protocol.protobuf.ExecutionCancelRequestPBOrBuilder> 
        getExecteCancelFieldBuilder() {
      if (execteCancelBuilder_ == null) {
        if (!(messageCase_ == 5)) {
          message_ = moonbox.protocol.protobuf.ExecutionCancelRequestPB.getDefaultInstance();
        }
        execteCancelBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            moonbox.protocol.protobuf.ExecutionCancelRequestPB, moonbox.protocol.protobuf.ExecutionCancelRequestPB.Builder, moonbox.protocol.protobuf.ExecutionCancelRequestPBOrBuilder>(
                (moonbox.protocol.protobuf.ExecutionCancelRequestPB) message_,
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      messageCase_ = 5;
      onChanged();;
      return execteCancelBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:moonbox.AppRequestMessage)
  }

  // @@protoc_insertion_point(class_scope:moonbox.AppRequestMessage)
  private static final moonbox.protocol.protobuf.AppRequestMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new moonbox.protocol.protobuf.AppRequestMessage();
  }

  public static moonbox.protocol.protobuf.AppRequestMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AppRequestMessage>
      PARSER = new com.google.protobuf.AbstractParser<AppRequestMessage>() {
    @java.lang.Override
    public AppRequestMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AppRequestMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AppRequestMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AppRequestMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public moonbox.protocol.protobuf.AppRequestMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

