// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_base.proto

package moonbox.protocol.protobuf;

/**
 * Protobuf type {@code moonbox.ArrayTypePB}
 */
public  final class ArrayTypePB extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:moonbox.ArrayTypePB)
    ArrayTypePBOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ArrayTypePB.newBuilder() to construct.
  private ArrayTypePB(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ArrayTypePB() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ArrayTypePB(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            moonbox.protocol.protobuf.DataTypePB.Builder subBuilder = null;
            if (elementType_ != null) {
              subBuilder = elementType_.toBuilder();
            }
            elementType_ = input.readMessage(moonbox.protocol.protobuf.DataTypePB.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(elementType_);
              elementType_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return moonbox.protocol.protobuf.DataBase.internal_static_moonbox_ArrayTypePB_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return moonbox.protocol.protobuf.DataBase.internal_static_moonbox_ArrayTypePB_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            moonbox.protocol.protobuf.ArrayTypePB.class, moonbox.protocol.protobuf.ArrayTypePB.Builder.class);
  }

  public static final int ELEMENT_TYPE_FIELD_NUMBER = 1;
  private moonbox.protocol.protobuf.DataTypePB elementType_;
  /**
   * <code>.moonbox.DataTypePB element_type = 1;</code>
   */
  public boolean hasElementType() {
    return elementType_ != null;
  }
  /**
   * <code>.moonbox.DataTypePB element_type = 1;</code>
   */
  public moonbox.protocol.protobuf.DataTypePB getElementType() {
    return elementType_ == null ? moonbox.protocol.protobuf.DataTypePB.getDefaultInstance() : elementType_;
  }
  /**
   * <code>.moonbox.DataTypePB element_type = 1;</code>
   */
  public moonbox.protocol.protobuf.DataTypePBOrBuilder getElementTypeOrBuilder() {
    return getElementType();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (elementType_ != null) {
      output.writeMessage(1, getElementType());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (elementType_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getElementType());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof moonbox.protocol.protobuf.ArrayTypePB)) {
      return super.equals(obj);
    }
    moonbox.protocol.protobuf.ArrayTypePB other = (moonbox.protocol.protobuf.ArrayTypePB) obj;

    boolean result = true;
    result = result && (hasElementType() == other.hasElementType());
    if (hasElementType()) {
      result = result && getElementType()
          .equals(other.getElementType());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasElementType()) {
      hash = (37 * hash) + ELEMENT_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getElementType().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static moonbox.protocol.protobuf.ArrayTypePB parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static moonbox.protocol.protobuf.ArrayTypePB parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static moonbox.protocol.protobuf.ArrayTypePB parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static moonbox.protocol.protobuf.ArrayTypePB parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static moonbox.protocol.protobuf.ArrayTypePB parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static moonbox.protocol.protobuf.ArrayTypePB parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static moonbox.protocol.protobuf.ArrayTypePB parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static moonbox.protocol.protobuf.ArrayTypePB parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static moonbox.protocol.protobuf.ArrayTypePB parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static moonbox.protocol.protobuf.ArrayTypePB parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static moonbox.protocol.protobuf.ArrayTypePB parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static moonbox.protocol.protobuf.ArrayTypePB parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(moonbox.protocol.protobuf.ArrayTypePB prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code moonbox.ArrayTypePB}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:moonbox.ArrayTypePB)
      moonbox.protocol.protobuf.ArrayTypePBOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return moonbox.protocol.protobuf.DataBase.internal_static_moonbox_ArrayTypePB_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return moonbox.protocol.protobuf.DataBase.internal_static_moonbox_ArrayTypePB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              moonbox.protocol.protobuf.ArrayTypePB.class, moonbox.protocol.protobuf.ArrayTypePB.Builder.class);
    }

    // Construct using moonbox.protocol.protobuf.ArrayTypePB.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (elementTypeBuilder_ == null) {
        elementType_ = null;
      } else {
        elementType_ = null;
        elementTypeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return moonbox.protocol.protobuf.DataBase.internal_static_moonbox_ArrayTypePB_descriptor;
    }

    @java.lang.Override
    public moonbox.protocol.protobuf.ArrayTypePB getDefaultInstanceForType() {
      return moonbox.protocol.protobuf.ArrayTypePB.getDefaultInstance();
    }

    @java.lang.Override
    public moonbox.protocol.protobuf.ArrayTypePB build() {
      moonbox.protocol.protobuf.ArrayTypePB result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public moonbox.protocol.protobuf.ArrayTypePB buildPartial() {
      moonbox.protocol.protobuf.ArrayTypePB result = new moonbox.protocol.protobuf.ArrayTypePB(this);
      if (elementTypeBuilder_ == null) {
        result.elementType_ = elementType_;
      } else {
        result.elementType_ = elementTypeBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof moonbox.protocol.protobuf.ArrayTypePB) {
        return mergeFrom((moonbox.protocol.protobuf.ArrayTypePB)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(moonbox.protocol.protobuf.ArrayTypePB other) {
      if (other == moonbox.protocol.protobuf.ArrayTypePB.getDefaultInstance()) return this;
      if (other.hasElementType()) {
        mergeElementType(other.getElementType());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      moonbox.protocol.protobuf.ArrayTypePB parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (moonbox.protocol.protobuf.ArrayTypePB) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private moonbox.protocol.protobuf.DataTypePB elementType_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        moonbox.protocol.protobuf.DataTypePB, moonbox.protocol.protobuf.DataTypePB.Builder, moonbox.protocol.protobuf.DataTypePBOrBuilder> elementTypeBuilder_;
    /**
     * <code>.moonbox.DataTypePB element_type = 1;</code>
     */
    public boolean hasElementType() {
      return elementTypeBuilder_ != null || elementType_ != null;
    }
    /**
     * <code>.moonbox.DataTypePB element_type = 1;</code>
     */
    public moonbox.protocol.protobuf.DataTypePB getElementType() {
      if (elementTypeBuilder_ == null) {
        return elementType_ == null ? moonbox.protocol.protobuf.DataTypePB.getDefaultInstance() : elementType_;
      } else {
        return elementTypeBuilder_.getMessage();
      }
    }
    /**
     * <code>.moonbox.DataTypePB element_type = 1;</code>
     */
    public Builder setElementType(moonbox.protocol.protobuf.DataTypePB value) {
      if (elementTypeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        elementType_ = value;
        onChanged();
      } else {
        elementTypeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.moonbox.DataTypePB element_type = 1;</code>
     */
    public Builder setElementType(
        moonbox.protocol.protobuf.DataTypePB.Builder builderForValue) {
      if (elementTypeBuilder_ == null) {
        elementType_ = builderForValue.build();
        onChanged();
      } else {
        elementTypeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.moonbox.DataTypePB element_type = 1;</code>
     */
    public Builder mergeElementType(moonbox.protocol.protobuf.DataTypePB value) {
      if (elementTypeBuilder_ == null) {
        if (elementType_ != null) {
          elementType_ =
            moonbox.protocol.protobuf.DataTypePB.newBuilder(elementType_).mergeFrom(value).buildPartial();
        } else {
          elementType_ = value;
        }
        onChanged();
      } else {
        elementTypeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.moonbox.DataTypePB element_type = 1;</code>
     */
    public Builder clearElementType() {
      if (elementTypeBuilder_ == null) {
        elementType_ = null;
        onChanged();
      } else {
        elementType_ = null;
        elementTypeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.moonbox.DataTypePB element_type = 1;</code>
     */
    public moonbox.protocol.protobuf.DataTypePB.Builder getElementTypeBuilder() {
      
      onChanged();
      return getElementTypeFieldBuilder().getBuilder();
    }
    /**
     * <code>.moonbox.DataTypePB element_type = 1;</code>
     */
    public moonbox.protocol.protobuf.DataTypePBOrBuilder getElementTypeOrBuilder() {
      if (elementTypeBuilder_ != null) {
        return elementTypeBuilder_.getMessageOrBuilder();
      } else {
        return elementType_ == null ?
            moonbox.protocol.protobuf.DataTypePB.getDefaultInstance() : elementType_;
      }
    }
    /**
     * <code>.moonbox.DataTypePB element_type = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        moonbox.protocol.protobuf.DataTypePB, moonbox.protocol.protobuf.DataTypePB.Builder, moonbox.protocol.protobuf.DataTypePBOrBuilder> 
        getElementTypeFieldBuilder() {
      if (elementTypeBuilder_ == null) {
        elementTypeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            moonbox.protocol.protobuf.DataTypePB, moonbox.protocol.protobuf.DataTypePB.Builder, moonbox.protocol.protobuf.DataTypePBOrBuilder>(
                getElementType(),
                getParentForChildren(),
                isClean());
        elementType_ = null;
      }
      return elementTypeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:moonbox.ArrayTypePB)
  }

  // @@protoc_insertion_point(class_scope:moonbox.ArrayTypePB)
  private static final moonbox.protocol.protobuf.ArrayTypePB DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new moonbox.protocol.protobuf.ArrayTypePB();
  }

  public static moonbox.protocol.protobuf.ArrayTypePB getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ArrayTypePB>
      PARSER = new com.google.protobuf.AbstractParser<ArrayTypePB>() {
    @java.lang.Override
    public ArrayTypePB parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ArrayTypePB(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ArrayTypePB> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ArrayTypePB> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public moonbox.protocol.protobuf.ArrayTypePB getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

