// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_base.proto

package moonbox.protocol.protobuf;

/**
 * Protobuf type {@code moonbox.BigDecimalPB}
 */
public  final class BigDecimalPB extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:moonbox.BigDecimalPB)
    BigDecimalPBOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BigDecimalPB.newBuilder() to construct.
  private BigDecimalPB(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BigDecimalPB() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BigDecimalPB(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            moonbox.protocol.protobuf.BigIntegerPB.Builder subBuilder = null;
            if (bigInteger_ != null) {
              subBuilder = bigInteger_.toBuilder();
            }
            bigInteger_ = input.readMessage(moonbox.protocol.protobuf.BigIntegerPB.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(bigInteger_);
              bigInteger_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return moonbox.protocol.protobuf.DataBase.internal_static_moonbox_BigDecimalPB_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return moonbox.protocol.protobuf.DataBase.internal_static_moonbox_BigDecimalPB_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            moonbox.protocol.protobuf.BigDecimalPB.class, moonbox.protocol.protobuf.BigDecimalPB.Builder.class);
  }

  public static final int BIG_INTEGER_FIELD_NUMBER = 1;
  private moonbox.protocol.protobuf.BigIntegerPB bigInteger_;
  /**
   * <code>.moonbox.BigIntegerPB big_integer = 1;</code>
   */
  public boolean hasBigInteger() {
    return bigInteger_ != null;
  }
  /**
   * <code>.moonbox.BigIntegerPB big_integer = 1;</code>
   */
  public moonbox.protocol.protobuf.BigIntegerPB getBigInteger() {
    return bigInteger_ == null ? moonbox.protocol.protobuf.BigIntegerPB.getDefaultInstance() : bigInteger_;
  }
  /**
   * <code>.moonbox.BigIntegerPB big_integer = 1;</code>
   */
  public moonbox.protocol.protobuf.BigIntegerPBOrBuilder getBigIntegerOrBuilder() {
    return getBigInteger();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (bigInteger_ != null) {
      output.writeMessage(1, getBigInteger());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (bigInteger_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBigInteger());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof moonbox.protocol.protobuf.BigDecimalPB)) {
      return super.equals(obj);
    }
    moonbox.protocol.protobuf.BigDecimalPB other = (moonbox.protocol.protobuf.BigDecimalPB) obj;

    boolean result = true;
    result = result && (hasBigInteger() == other.hasBigInteger());
    if (hasBigInteger()) {
      result = result && getBigInteger()
          .equals(other.getBigInteger());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBigInteger()) {
      hash = (37 * hash) + BIG_INTEGER_FIELD_NUMBER;
      hash = (53 * hash) + getBigInteger().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static moonbox.protocol.protobuf.BigDecimalPB parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static moonbox.protocol.protobuf.BigDecimalPB parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static moonbox.protocol.protobuf.BigDecimalPB parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static moonbox.protocol.protobuf.BigDecimalPB parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static moonbox.protocol.protobuf.BigDecimalPB parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static moonbox.protocol.protobuf.BigDecimalPB parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static moonbox.protocol.protobuf.BigDecimalPB parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static moonbox.protocol.protobuf.BigDecimalPB parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static moonbox.protocol.protobuf.BigDecimalPB parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static moonbox.protocol.protobuf.BigDecimalPB parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static moonbox.protocol.protobuf.BigDecimalPB parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static moonbox.protocol.protobuf.BigDecimalPB parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(moonbox.protocol.protobuf.BigDecimalPB prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code moonbox.BigDecimalPB}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:moonbox.BigDecimalPB)
      moonbox.protocol.protobuf.BigDecimalPBOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return moonbox.protocol.protobuf.DataBase.internal_static_moonbox_BigDecimalPB_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return moonbox.protocol.protobuf.DataBase.internal_static_moonbox_BigDecimalPB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              moonbox.protocol.protobuf.BigDecimalPB.class, moonbox.protocol.protobuf.BigDecimalPB.Builder.class);
    }

    // Construct using moonbox.protocol.protobuf.BigDecimalPB.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (bigIntegerBuilder_ == null) {
        bigInteger_ = null;
      } else {
        bigInteger_ = null;
        bigIntegerBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return moonbox.protocol.protobuf.DataBase.internal_static_moonbox_BigDecimalPB_descriptor;
    }

    @java.lang.Override
    public moonbox.protocol.protobuf.BigDecimalPB getDefaultInstanceForType() {
      return moonbox.protocol.protobuf.BigDecimalPB.getDefaultInstance();
    }

    @java.lang.Override
    public moonbox.protocol.protobuf.BigDecimalPB build() {
      moonbox.protocol.protobuf.BigDecimalPB result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public moonbox.protocol.protobuf.BigDecimalPB buildPartial() {
      moonbox.protocol.protobuf.BigDecimalPB result = new moonbox.protocol.protobuf.BigDecimalPB(this);
      if (bigIntegerBuilder_ == null) {
        result.bigInteger_ = bigInteger_;
      } else {
        result.bigInteger_ = bigIntegerBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof moonbox.protocol.protobuf.BigDecimalPB) {
        return mergeFrom((moonbox.protocol.protobuf.BigDecimalPB)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(moonbox.protocol.protobuf.BigDecimalPB other) {
      if (other == moonbox.protocol.protobuf.BigDecimalPB.getDefaultInstance()) return this;
      if (other.hasBigInteger()) {
        mergeBigInteger(other.getBigInteger());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      moonbox.protocol.protobuf.BigDecimalPB parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (moonbox.protocol.protobuf.BigDecimalPB) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private moonbox.protocol.protobuf.BigIntegerPB bigInteger_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        moonbox.protocol.protobuf.BigIntegerPB, moonbox.protocol.protobuf.BigIntegerPB.Builder, moonbox.protocol.protobuf.BigIntegerPBOrBuilder> bigIntegerBuilder_;
    /**
     * <code>.moonbox.BigIntegerPB big_integer = 1;</code>
     */
    public boolean hasBigInteger() {
      return bigIntegerBuilder_ != null || bigInteger_ != null;
    }
    /**
     * <code>.moonbox.BigIntegerPB big_integer = 1;</code>
     */
    public moonbox.protocol.protobuf.BigIntegerPB getBigInteger() {
      if (bigIntegerBuilder_ == null) {
        return bigInteger_ == null ? moonbox.protocol.protobuf.BigIntegerPB.getDefaultInstance() : bigInteger_;
      } else {
        return bigIntegerBuilder_.getMessage();
      }
    }
    /**
     * <code>.moonbox.BigIntegerPB big_integer = 1;</code>
     */
    public Builder setBigInteger(moonbox.protocol.protobuf.BigIntegerPB value) {
      if (bigIntegerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        bigInteger_ = value;
        onChanged();
      } else {
        bigIntegerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.moonbox.BigIntegerPB big_integer = 1;</code>
     */
    public Builder setBigInteger(
        moonbox.protocol.protobuf.BigIntegerPB.Builder builderForValue) {
      if (bigIntegerBuilder_ == null) {
        bigInteger_ = builderForValue.build();
        onChanged();
      } else {
        bigIntegerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.moonbox.BigIntegerPB big_integer = 1;</code>
     */
    public Builder mergeBigInteger(moonbox.protocol.protobuf.BigIntegerPB value) {
      if (bigIntegerBuilder_ == null) {
        if (bigInteger_ != null) {
          bigInteger_ =
            moonbox.protocol.protobuf.BigIntegerPB.newBuilder(bigInteger_).mergeFrom(value).buildPartial();
        } else {
          bigInteger_ = value;
        }
        onChanged();
      } else {
        bigIntegerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.moonbox.BigIntegerPB big_integer = 1;</code>
     */
    public Builder clearBigInteger() {
      if (bigIntegerBuilder_ == null) {
        bigInteger_ = null;
        onChanged();
      } else {
        bigInteger_ = null;
        bigIntegerBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.moonbox.BigIntegerPB big_integer = 1;</code>
     */
    public moonbox.protocol.protobuf.BigIntegerPB.Builder getBigIntegerBuilder() {
      
      onChanged();
      return getBigIntegerFieldBuilder().getBuilder();
    }
    /**
     * <code>.moonbox.BigIntegerPB big_integer = 1;</code>
     */
    public moonbox.protocol.protobuf.BigIntegerPBOrBuilder getBigIntegerOrBuilder() {
      if (bigIntegerBuilder_ != null) {
        return bigIntegerBuilder_.getMessageOrBuilder();
      } else {
        return bigInteger_ == null ?
            moonbox.protocol.protobuf.BigIntegerPB.getDefaultInstance() : bigInteger_;
      }
    }
    /**
     * <code>.moonbox.BigIntegerPB big_integer = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        moonbox.protocol.protobuf.BigIntegerPB, moonbox.protocol.protobuf.BigIntegerPB.Builder, moonbox.protocol.protobuf.BigIntegerPBOrBuilder> 
        getBigIntegerFieldBuilder() {
      if (bigIntegerBuilder_ == null) {
        bigIntegerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            moonbox.protocol.protobuf.BigIntegerPB, moonbox.protocol.protobuf.BigIntegerPB.Builder, moonbox.protocol.protobuf.BigIntegerPBOrBuilder>(
                getBigInteger(),
                getParentForChildren(),
                isClean());
        bigInteger_ = null;
      }
      return bigIntegerBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:moonbox.BigDecimalPB)
  }

  // @@protoc_insertion_point(class_scope:moonbox.BigDecimalPB)
  private static final moonbox.protocol.protobuf.BigDecimalPB DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new moonbox.protocol.protobuf.BigDecimalPB();
  }

  public static moonbox.protocol.protobuf.BigDecimalPB getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BigDecimalPB>
      PARSER = new com.google.protobuf.AbstractParser<BigDecimalPB>() {
    @java.lang.Override
    public BigDecimalPB parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BigDecimalPB(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BigDecimalPB> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BigDecimalPB> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public moonbox.protocol.protobuf.BigDecimalPB getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

