// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_base.proto

package moonbox.protocol.protobuf;

public interface BigDecimalPBOrBuilder extends
    // @@protoc_insertion_point(interface_extends:moonbox.BigDecimalPB)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.moonbox.BigIntegerPB big_integer = 1;</code>
   */
  boolean hasBigInteger();
  /**
   * <code>.moonbox.BigIntegerPB big_integer = 1;</code>
   */
  moonbox.protocol.protobuf.BigIntegerPB getBigInteger();
  /**
   * <code>.moonbox.BigIntegerPB big_integer = 1;</code>
   */
  moonbox.protocol.protobuf.BigIntegerPBOrBuilder getBigIntegerOrBuilder();
}
