// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app_base.proto

package moonbox.protocol.protobuf;

public interface CloseSessionResponsePBOrBuilder extends
    // @@protoc_insertion_point(interface_extends:moonbox.CloseSessionResponsePB)
    com.google.protobuf.MessageOrBuilder {
}
