// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: master_base.proto

package moonbox.protocol.protobuf;

public interface HostPortPBOrBuilder extends
    // @@protoc_insertion_point(interface_extends:moonbox.HostPortPB)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string host = 1;</code>
   */
  java.lang.String getHost();
  /**
   * <code>string host = 1;</code>
   */
  com.google.protobuf.ByteString
      getHostBytes();

  /**
   * <code>uint32 port = 2;</code>
   */
  int getPort();
}
