// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_base.proto

package moonbox.protocol.protobuf;

public interface MapPBOrBuilder extends
    // @@protoc_insertion_point(interface_extends:moonbox.MapPB)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .moonbox.Value&gt; values = 1;</code>
   */
  int getValuesCount();
  /**
   * <code>map&lt;string, .moonbox.Value&gt; values = 1;</code>
   */
  boolean containsValues(
      java.lang.String key);
  /**
   * Use {@link #getValuesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, moonbox.protocol.protobuf.Value>
  getValues();
  /**
   * <code>map&lt;string, .moonbox.Value&gt; values = 1;</code>
   */
  java.util.Map<java.lang.String, moonbox.protocol.protobuf.Value>
  getValuesMap();
  /**
   * <code>map&lt;string, .moonbox.Value&gt; values = 1;</code>
   */

  moonbox.protocol.protobuf.Value getValuesOrDefault(
      java.lang.String key,
      moonbox.protocol.protobuf.Value defaultValue);
  /**
   * <code>map&lt;string, .moonbox.Value&gt; values = 1;</code>
   */

  moonbox.protocol.protobuf.Value getValuesOrThrow(
      java.lang.String key);
}
