// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_base.proto

package moonbox.protocol.protobuf;

public interface MapTypePBOrBuilder extends
    // @@protoc_insertion_point(interface_extends:moonbox.MapTypePB)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.moonbox.DataTypePB key_type = 1;</code>
   */
  boolean hasKeyType();
  /**
   * <code>.moonbox.DataTypePB key_type = 1;</code>
   */
  moonbox.protocol.protobuf.DataTypePB getKeyType();
  /**
   * <code>.moonbox.DataTypePB key_type = 1;</code>
   */
  moonbox.protocol.protobuf.DataTypePBOrBuilder getKeyTypeOrBuilder();

  /**
   * <code>.moonbox.DataTypePB value_type = 2;</code>
   */
  boolean hasValueType();
  /**
   * <code>.moonbox.DataTypePB value_type = 2;</code>
   */
  moonbox.protocol.protobuf.DataTypePB getValueType();
  /**
   * <code>.moonbox.DataTypePB value_type = 2;</code>
   */
  moonbox.protocol.protobuf.DataTypePBOrBuilder getValueTypeOrBuilder();
}
