// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: master_base.proto

package moonbox.protocol.protobuf;

public final class MasterBase {
  private MasterBase() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_moonbox_AccessRequestPB_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_moonbox_AccessRequestPB_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_moonbox_AccessResponsePB_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_moonbox_AccessResponsePB_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_moonbox_SessionPB_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_moonbox_SessionPB_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_moonbox_SessionPB_SessionEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_moonbox_SessionPB_SessionEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_moonbox_HostPortPB_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_moonbox_HostPortPB_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021master_base.proto\022\007moonbox\"Y\n\017AccessRe" +
      "questPB\022\020\n\010username\030\001 \001(\t\022\020\n\010password\030\002 " +
      "\001(\t\022\020\n\010app_type\030\003 \001(\t\022\020\n\010app_name\030\004 \001(\t\"" +
      "_\n\020AccessResponsePB\022&\n\thost_port\030\001 \001(\0132\023" +
      ".moonbox.HostPortPB\022#\n\007session\030\002 \001(\0132\022.m" +
      "oonbox.SessionPB\"m\n\tSessionPB\0220\n\007session" +
      "\030\001 \003(\0132\037.moonbox.SessionPB.SessionEntry\032" +
      ".\n\014SessionEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 " +
      "\001(\t:\0028\001\"(\n\nHostPortPB\022\014\n\004host\030\001 \001(\t\022\014\n\004p" +
      "ort\030\002 \001(\rB\035\n\031moonbox.protocol.protobufP\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_moonbox_AccessRequestPB_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_moonbox_AccessRequestPB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_moonbox_AccessRequestPB_descriptor,
        new java.lang.String[] { "Username", "Password", "AppType", "AppName", });
    internal_static_moonbox_AccessResponsePB_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_moonbox_AccessResponsePB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_moonbox_AccessResponsePB_descriptor,
        new java.lang.String[] { "HostPort", "Session", });
    internal_static_moonbox_SessionPB_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_moonbox_SessionPB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_moonbox_SessionPB_descriptor,
        new java.lang.String[] { "Session", });
    internal_static_moonbox_SessionPB_SessionEntry_descriptor =
      internal_static_moonbox_SessionPB_descriptor.getNestedTypes().get(0);
    internal_static_moonbox_SessionPB_SessionEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_moonbox_SessionPB_SessionEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_moonbox_HostPortPB_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_moonbox_HostPortPB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_moonbox_HostPortPB_descriptor,
        new java.lang.String[] { "Host", "Port", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
