// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_base.proto

package moonbox.protocol.protobuf;

public interface NullTypePBOrBuilder extends
    // @@protoc_insertion_point(interface_extends:moonbox.NullTypePB)
    com.google.protobuf.MessageOrBuilder {
}
