// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_base.proto

package moonbox.protocol.protobuf;

public interface ObjectTypePBOrBuilder extends
    // @@protoc_insertion_point(interface_extends:moonbox.ObjectTypePB)
    com.google.protobuf.MessageOrBuilder {
}
