// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_base.proto

package moonbox.protocol.protobuf;

public interface ResultDataPBOrBuilder extends
    // @@protoc_insertion_point(interface_extends:moonbox.ResultDataPB)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.moonbox.StructTypePB schema = 1;</code>
   */
  boolean hasSchema();
  /**
   * <code>.moonbox.StructTypePB schema = 1;</code>
   */
  moonbox.protocol.protobuf.StructTypePB getSchema();
  /**
   * <code>.moonbox.StructTypePB schema = 1;</code>
   */
  moonbox.protocol.protobuf.StructTypePBOrBuilder getSchemaOrBuilder();

  /**
   * <code>repeated .moonbox.RowPB rows = 2;</code>
   */
  java.util.List<moonbox.protocol.protobuf.RowPB> 
      getRowsList();
  /**
   * <code>repeated .moonbox.RowPB rows = 2;</code>
   */
  moonbox.protocol.protobuf.RowPB getRows(int index);
  /**
   * <code>repeated .moonbox.RowPB rows = 2;</code>
   */
  int getRowsCount();
  /**
   * <code>repeated .moonbox.RowPB rows = 2;</code>
   */
  java.util.List<? extends moonbox.protocol.protobuf.RowPBOrBuilder> 
      getRowsOrBuilderList();
  /**
   * <code>repeated .moonbox.RowPB rows = 2;</code>
   */
  moonbox.protocol.protobuf.RowPBOrBuilder getRowsOrBuilder(
      int index);
}
