// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_base.proto

package moonbox.protocol.protobuf;

public interface StructFieldPBOrBuilder extends
    // @@protoc_insertion_point(interface_extends:moonbox.StructFieldPB)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.moonbox.DataTypePB data_type = 2;</code>
   */
  boolean hasDataType();
  /**
   * <code>.moonbox.DataTypePB data_type = 2;</code>
   */
  moonbox.protocol.protobuf.DataTypePB getDataType();
  /**
   * <code>.moonbox.DataTypePB data_type = 2;</code>
   */
  moonbox.protocol.protobuf.DataTypePBOrBuilder getDataTypeOrBuilder();

  /**
   * <code>bool nullable = 3;</code>
   */
  boolean getNullable();

  /**
   * <code>string meta_data = 4;</code>
   */
  java.lang.String getMetaData();
  /**
   * <code>string meta_data = 4;</code>
   */
  com.google.protobuf.ByteString
      getMetaDataBytes();
}
