// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_base.proto

package moonbox.protocol.protobuf;

/**
 * Protobuf type {@code moonbox.StructFieldPB}
 */
public  final class StructFieldPB extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:moonbox.StructFieldPB)
    StructFieldPBOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StructFieldPB.newBuilder() to construct.
  private StructFieldPB(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StructFieldPB() {
    name_ = "";
    nullable_ = false;
    metaData_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StructFieldPB(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            moonbox.protocol.protobuf.DataTypePB.Builder subBuilder = null;
            if (dataType_ != null) {
              subBuilder = dataType_.toBuilder();
            }
            dataType_ = input.readMessage(moonbox.protocol.protobuf.DataTypePB.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dataType_);
              dataType_ = subBuilder.buildPartial();
            }

            break;
          }
          case 24: {

            nullable_ = input.readBool();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            metaData_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return moonbox.protocol.protobuf.DataBase.internal_static_moonbox_StructFieldPB_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return moonbox.protocol.protobuf.DataBase.internal_static_moonbox_StructFieldPB_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            moonbox.protocol.protobuf.StructFieldPB.class, moonbox.protocol.protobuf.StructFieldPB.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATA_TYPE_FIELD_NUMBER = 2;
  private moonbox.protocol.protobuf.DataTypePB dataType_;
  /**
   * <code>.moonbox.DataTypePB data_type = 2;</code>
   */
  public boolean hasDataType() {
    return dataType_ != null;
  }
  /**
   * <code>.moonbox.DataTypePB data_type = 2;</code>
   */
  public moonbox.protocol.protobuf.DataTypePB getDataType() {
    return dataType_ == null ? moonbox.protocol.protobuf.DataTypePB.getDefaultInstance() : dataType_;
  }
  /**
   * <code>.moonbox.DataTypePB data_type = 2;</code>
   */
  public moonbox.protocol.protobuf.DataTypePBOrBuilder getDataTypeOrBuilder() {
    return getDataType();
  }

  public static final int NULLABLE_FIELD_NUMBER = 3;
  private boolean nullable_;
  /**
   * <code>bool nullable = 3;</code>
   */
  public boolean getNullable() {
    return nullable_;
  }

  public static final int META_DATA_FIELD_NUMBER = 4;
  private volatile java.lang.Object metaData_;
  /**
   * <code>string meta_data = 4;</code>
   */
  public java.lang.String getMetaData() {
    java.lang.Object ref = metaData_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      metaData_ = s;
      return s;
    }
  }
  /**
   * <code>string meta_data = 4;</code>
   */
  public com.google.protobuf.ByteString
      getMetaDataBytes() {
    java.lang.Object ref = metaData_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      metaData_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (dataType_ != null) {
      output.writeMessage(2, getDataType());
    }
    if (nullable_ != false) {
      output.writeBool(3, nullable_);
    }
    if (!getMetaDataBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, metaData_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (dataType_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getDataType());
    }
    if (nullable_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, nullable_);
    }
    if (!getMetaDataBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, metaData_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof moonbox.protocol.protobuf.StructFieldPB)) {
      return super.equals(obj);
    }
    moonbox.protocol.protobuf.StructFieldPB other = (moonbox.protocol.protobuf.StructFieldPB) obj;

    boolean result = true;
    result = result && getName()
        .equals(other.getName());
    result = result && (hasDataType() == other.hasDataType());
    if (hasDataType()) {
      result = result && getDataType()
          .equals(other.getDataType());
    }
    result = result && (getNullable()
        == other.getNullable());
    result = result && getMetaData()
        .equals(other.getMetaData());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (hasDataType()) {
      hash = (37 * hash) + DATA_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getDataType().hashCode();
    }
    hash = (37 * hash) + NULLABLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getNullable());
    hash = (37 * hash) + META_DATA_FIELD_NUMBER;
    hash = (53 * hash) + getMetaData().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static moonbox.protocol.protobuf.StructFieldPB parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static moonbox.protocol.protobuf.StructFieldPB parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static moonbox.protocol.protobuf.StructFieldPB parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static moonbox.protocol.protobuf.StructFieldPB parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static moonbox.protocol.protobuf.StructFieldPB parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static moonbox.protocol.protobuf.StructFieldPB parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static moonbox.protocol.protobuf.StructFieldPB parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static moonbox.protocol.protobuf.StructFieldPB parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static moonbox.protocol.protobuf.StructFieldPB parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static moonbox.protocol.protobuf.StructFieldPB parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static moonbox.protocol.protobuf.StructFieldPB parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static moonbox.protocol.protobuf.StructFieldPB parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(moonbox.protocol.protobuf.StructFieldPB prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code moonbox.StructFieldPB}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:moonbox.StructFieldPB)
      moonbox.protocol.protobuf.StructFieldPBOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return moonbox.protocol.protobuf.DataBase.internal_static_moonbox_StructFieldPB_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return moonbox.protocol.protobuf.DataBase.internal_static_moonbox_StructFieldPB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              moonbox.protocol.protobuf.StructFieldPB.class, moonbox.protocol.protobuf.StructFieldPB.Builder.class);
    }

    // Construct using moonbox.protocol.protobuf.StructFieldPB.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      if (dataTypeBuilder_ == null) {
        dataType_ = null;
      } else {
        dataType_ = null;
        dataTypeBuilder_ = null;
      }
      nullable_ = false;

      metaData_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return moonbox.protocol.protobuf.DataBase.internal_static_moonbox_StructFieldPB_descriptor;
    }

    @java.lang.Override
    public moonbox.protocol.protobuf.StructFieldPB getDefaultInstanceForType() {
      return moonbox.protocol.protobuf.StructFieldPB.getDefaultInstance();
    }

    @java.lang.Override
    public moonbox.protocol.protobuf.StructFieldPB build() {
      moonbox.protocol.protobuf.StructFieldPB result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public moonbox.protocol.protobuf.StructFieldPB buildPartial() {
      moonbox.protocol.protobuf.StructFieldPB result = new moonbox.protocol.protobuf.StructFieldPB(this);
      result.name_ = name_;
      if (dataTypeBuilder_ == null) {
        result.dataType_ = dataType_;
      } else {
        result.dataType_ = dataTypeBuilder_.build();
      }
      result.nullable_ = nullable_;
      result.metaData_ = metaData_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof moonbox.protocol.protobuf.StructFieldPB) {
        return mergeFrom((moonbox.protocol.protobuf.StructFieldPB)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(moonbox.protocol.protobuf.StructFieldPB other) {
      if (other == moonbox.protocol.protobuf.StructFieldPB.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.hasDataType()) {
        mergeDataType(other.getDataType());
      }
      if (other.getNullable() != false) {
        setNullable(other.getNullable());
      }
      if (!other.getMetaData().isEmpty()) {
        metaData_ = other.metaData_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      moonbox.protocol.protobuf.StructFieldPB parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (moonbox.protocol.protobuf.StructFieldPB) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private moonbox.protocol.protobuf.DataTypePB dataType_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        moonbox.protocol.protobuf.DataTypePB, moonbox.protocol.protobuf.DataTypePB.Builder, moonbox.protocol.protobuf.DataTypePBOrBuilder> dataTypeBuilder_;
    /**
     * <code>.moonbox.DataTypePB data_type = 2;</code>
     */
    public boolean hasDataType() {
      return dataTypeBuilder_ != null || dataType_ != null;
    }
    /**
     * <code>.moonbox.DataTypePB data_type = 2;</code>
     */
    public moonbox.protocol.protobuf.DataTypePB getDataType() {
      if (dataTypeBuilder_ == null) {
        return dataType_ == null ? moonbox.protocol.protobuf.DataTypePB.getDefaultInstance() : dataType_;
      } else {
        return dataTypeBuilder_.getMessage();
      }
    }
    /**
     * <code>.moonbox.DataTypePB data_type = 2;</code>
     */
    public Builder setDataType(moonbox.protocol.protobuf.DataTypePB value) {
      if (dataTypeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataType_ = value;
        onChanged();
      } else {
        dataTypeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.moonbox.DataTypePB data_type = 2;</code>
     */
    public Builder setDataType(
        moonbox.protocol.protobuf.DataTypePB.Builder builderForValue) {
      if (dataTypeBuilder_ == null) {
        dataType_ = builderForValue.build();
        onChanged();
      } else {
        dataTypeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.moonbox.DataTypePB data_type = 2;</code>
     */
    public Builder mergeDataType(moonbox.protocol.protobuf.DataTypePB value) {
      if (dataTypeBuilder_ == null) {
        if (dataType_ != null) {
          dataType_ =
            moonbox.protocol.protobuf.DataTypePB.newBuilder(dataType_).mergeFrom(value).buildPartial();
        } else {
          dataType_ = value;
        }
        onChanged();
      } else {
        dataTypeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.moonbox.DataTypePB data_type = 2;</code>
     */
    public Builder clearDataType() {
      if (dataTypeBuilder_ == null) {
        dataType_ = null;
        onChanged();
      } else {
        dataType_ = null;
        dataTypeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.moonbox.DataTypePB data_type = 2;</code>
     */
    public moonbox.protocol.protobuf.DataTypePB.Builder getDataTypeBuilder() {
      
      onChanged();
      return getDataTypeFieldBuilder().getBuilder();
    }
    /**
     * <code>.moonbox.DataTypePB data_type = 2;</code>
     */
    public moonbox.protocol.protobuf.DataTypePBOrBuilder getDataTypeOrBuilder() {
      if (dataTypeBuilder_ != null) {
        return dataTypeBuilder_.getMessageOrBuilder();
      } else {
        return dataType_ == null ?
            moonbox.protocol.protobuf.DataTypePB.getDefaultInstance() : dataType_;
      }
    }
    /**
     * <code>.moonbox.DataTypePB data_type = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        moonbox.protocol.protobuf.DataTypePB, moonbox.protocol.protobuf.DataTypePB.Builder, moonbox.protocol.protobuf.DataTypePBOrBuilder> 
        getDataTypeFieldBuilder() {
      if (dataTypeBuilder_ == null) {
        dataTypeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            moonbox.protocol.protobuf.DataTypePB, moonbox.protocol.protobuf.DataTypePB.Builder, moonbox.protocol.protobuf.DataTypePBOrBuilder>(
                getDataType(),
                getParentForChildren(),
                isClean());
        dataType_ = null;
      }
      return dataTypeBuilder_;
    }

    private boolean nullable_ ;
    /**
     * <code>bool nullable = 3;</code>
     */
    public boolean getNullable() {
      return nullable_;
    }
    /**
     * <code>bool nullable = 3;</code>
     */
    public Builder setNullable(boolean value) {
      
      nullable_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool nullable = 3;</code>
     */
    public Builder clearNullable() {
      
      nullable_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object metaData_ = "";
    /**
     * <code>string meta_data = 4;</code>
     */
    public java.lang.String getMetaData() {
      java.lang.Object ref = metaData_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        metaData_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string meta_data = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMetaDataBytes() {
      java.lang.Object ref = metaData_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        metaData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string meta_data = 4;</code>
     */
    public Builder setMetaData(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      metaData_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string meta_data = 4;</code>
     */
    public Builder clearMetaData() {
      
      metaData_ = getDefaultInstance().getMetaData();
      onChanged();
      return this;
    }
    /**
     * <code>string meta_data = 4;</code>
     */
    public Builder setMetaDataBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      metaData_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:moonbox.StructFieldPB)
  }

  // @@protoc_insertion_point(class_scope:moonbox.StructFieldPB)
  private static final moonbox.protocol.protobuf.StructFieldPB DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new moonbox.protocol.protobuf.StructFieldPB();
  }

  public static moonbox.protocol.protobuf.StructFieldPB getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StructFieldPB>
      PARSER = new com.google.protobuf.AbstractParser<StructFieldPB>() {
    @java.lang.Override
    public StructFieldPB parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StructFieldPB(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StructFieldPB> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StructFieldPB> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public moonbox.protocol.protobuf.StructFieldPB getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

