// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_message.proto

package moonbox.message.protobuf;

public interface BatchQueryCancelOutboundOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.BatchQueryCancelOutbound)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string error = 1;</code>
   */
  java.lang.String getError();
  /**
   * <code>string error = 1;</code>
   */
  com.google.protobuf.ByteString
      getErrorBytes();
}
