// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_message.proto

package moonbox.message.protobuf;

public interface BDecimalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.BDecimal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 scale = 1;</code>
   */
  int getScale();

  /**
   * <code>.protobuf.BInteger int_val = 2;</code>
   */
  boolean hasIntVal();
  /**
   * <code>.protobuf.BInteger int_val = 2;</code>
   */
  moonbox.message.protobuf.BInteger getIntVal();
  /**
   * <code>.protobuf.BInteger int_val = 2;</code>
   */
  moonbox.message.protobuf.BIntegerOrBuilder getIntValOrBuilder();
}
