// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_message.proto

package moonbox.message.protobuf;

public interface InteractiveNextResultInboundOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.InteractiveNextResultInbound)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   */
  java.lang.String getToken();
  /**
   * <code>string token = 1;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <pre>
   *    string cursor = 3;
   *    int32 fetch_size = 4;
   * </pre>
   *
   * <code>string session_id = 2;</code>
   */
  java.lang.String getSessionId();
  /**
   * <pre>
   *    string cursor = 3;
   *    int32 fetch_size = 4;
   * </pre>
   *
   * <code>string session_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();
}
