// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_message.proto

package moonbox.message.protobuf;

public interface OpenSessionOutboundOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.OpenSessionOutbound)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string session_id = 1;</code>
   */
  java.lang.String getSessionId();
  /**
   * <code>string session_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>string worker_host = 2;</code>
   */
  java.lang.String getWorkerHost();
  /**
   * <code>string worker_host = 2;</code>
   */
  com.google.protobuf.ByteString
      getWorkerHostBytes();

  /**
   * <code>int32 worker_port = 3;</code>
   */
  int getWorkerPort();

  /**
   * <code>string error = 4;</code>
   */
  java.lang.String getError();
  /**
   * <code>string error = 4;</code>
   */
  com.google.protobuf.ByteString
      getErrorBytes();
}
