// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_message.proto

package moonbox.message.protobuf;

public interface BatchQueryProgressInboundOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.BatchQueryProgressInbound)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   */
  java.lang.String getToken();
  /**
   * <code>string token = 1;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>string job_id = 2;</code>
   */
  java.lang.String getJobId();
  /**
   * <code>string job_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getJobIdBytes();
}
