// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_message.proto

package moonbox.message.protobuf;

/**
 * <pre>
 * BigDecimal 
 * </pre>
 *
 * Protobuf type {@code protobuf.BDecimal}
 */
public  final class BDecimal extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protobuf.BDecimal)
    BDecimalOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BDecimal.newBuilder() to construct.
  private BDecimal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BDecimal() {
    scale_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BDecimal(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            scale_ = input.readInt32();
            break;
          }
          case 18: {
            moonbox.message.protobuf.BInteger.Builder subBuilder = null;
            if (intVal_ != null) {
              subBuilder = intVal_.toBuilder();
            }
            intVal_ = input.readMessage(moonbox.message.protobuf.BInteger.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(intVal_);
              intVal_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return moonbox.message.protobuf.ProtoMessageOuterClass.internal_static_protobuf_BDecimal_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return moonbox.message.protobuf.ProtoMessageOuterClass.internal_static_protobuf_BDecimal_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            moonbox.message.protobuf.BDecimal.class, moonbox.message.protobuf.BDecimal.Builder.class);
  }

  public static final int SCALE_FIELD_NUMBER = 1;
  private int scale_;
  /**
   * <code>int32 scale = 1;</code>
   */
  public int getScale() {
    return scale_;
  }

  public static final int INT_VAL_FIELD_NUMBER = 2;
  private moonbox.message.protobuf.BInteger intVal_;
  /**
   * <code>.protobuf.BInteger int_val = 2;</code>
   */
  public boolean hasIntVal() {
    return intVal_ != null;
  }
  /**
   * <code>.protobuf.BInteger int_val = 2;</code>
   */
  public moonbox.message.protobuf.BInteger getIntVal() {
    return intVal_ == null ? moonbox.message.protobuf.BInteger.getDefaultInstance() : intVal_;
  }
  /**
   * <code>.protobuf.BInteger int_val = 2;</code>
   */
  public moonbox.message.protobuf.BIntegerOrBuilder getIntValOrBuilder() {
    return getIntVal();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (scale_ != 0) {
      output.writeInt32(1, scale_);
    }
    if (intVal_ != null) {
      output.writeMessage(2, getIntVal());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (scale_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, scale_);
    }
    if (intVal_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getIntVal());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof moonbox.message.protobuf.BDecimal)) {
      return super.equals(obj);
    }
    moonbox.message.protobuf.BDecimal other = (moonbox.message.protobuf.BDecimal) obj;

    boolean result = true;
    result = result && (getScale()
        == other.getScale());
    result = result && (hasIntVal() == other.hasIntVal());
    if (hasIntVal()) {
      result = result && getIntVal()
          .equals(other.getIntVal());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SCALE_FIELD_NUMBER;
    hash = (53 * hash) + getScale();
    if (hasIntVal()) {
      hash = (37 * hash) + INT_VAL_FIELD_NUMBER;
      hash = (53 * hash) + getIntVal().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static moonbox.message.protobuf.BDecimal parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static moonbox.message.protobuf.BDecimal parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static moonbox.message.protobuf.BDecimal parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static moonbox.message.protobuf.BDecimal parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static moonbox.message.protobuf.BDecimal parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static moonbox.message.protobuf.BDecimal parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static moonbox.message.protobuf.BDecimal parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static moonbox.message.protobuf.BDecimal parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static moonbox.message.protobuf.BDecimal parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static moonbox.message.protobuf.BDecimal parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static moonbox.message.protobuf.BDecimal parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static moonbox.message.protobuf.BDecimal parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(moonbox.message.protobuf.BDecimal prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * BigDecimal 
   * </pre>
   *
   * Protobuf type {@code protobuf.BDecimal}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protobuf.BDecimal)
      moonbox.message.protobuf.BDecimalOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return moonbox.message.protobuf.ProtoMessageOuterClass.internal_static_protobuf_BDecimal_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return moonbox.message.protobuf.ProtoMessageOuterClass.internal_static_protobuf_BDecimal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              moonbox.message.protobuf.BDecimal.class, moonbox.message.protobuf.BDecimal.Builder.class);
    }

    // Construct using moonbox.message.protobuf.BDecimal.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      scale_ = 0;

      if (intValBuilder_ == null) {
        intVal_ = null;
      } else {
        intVal_ = null;
        intValBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return moonbox.message.protobuf.ProtoMessageOuterClass.internal_static_protobuf_BDecimal_descriptor;
    }

    public moonbox.message.protobuf.BDecimal getDefaultInstanceForType() {
      return moonbox.message.protobuf.BDecimal.getDefaultInstance();
    }

    public moonbox.message.protobuf.BDecimal build() {
      moonbox.message.protobuf.BDecimal result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public moonbox.message.protobuf.BDecimal buildPartial() {
      moonbox.message.protobuf.BDecimal result = new moonbox.message.protobuf.BDecimal(this);
      result.scale_ = scale_;
      if (intValBuilder_ == null) {
        result.intVal_ = intVal_;
      } else {
        result.intVal_ = intValBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof moonbox.message.protobuf.BDecimal) {
        return mergeFrom((moonbox.message.protobuf.BDecimal)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(moonbox.message.protobuf.BDecimal other) {
      if (other == moonbox.message.protobuf.BDecimal.getDefaultInstance()) return this;
      if (other.getScale() != 0) {
        setScale(other.getScale());
      }
      if (other.hasIntVal()) {
        mergeIntVal(other.getIntVal());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      moonbox.message.protobuf.BDecimal parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (moonbox.message.protobuf.BDecimal) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int scale_ ;
    /**
     * <code>int32 scale = 1;</code>
     */
    public int getScale() {
      return scale_;
    }
    /**
     * <code>int32 scale = 1;</code>
     */
    public Builder setScale(int value) {
      
      scale_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 scale = 1;</code>
     */
    public Builder clearScale() {
      
      scale_ = 0;
      onChanged();
      return this;
    }

    private moonbox.message.protobuf.BInteger intVal_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        moonbox.message.protobuf.BInteger, moonbox.message.protobuf.BInteger.Builder, moonbox.message.protobuf.BIntegerOrBuilder> intValBuilder_;
    /**
     * <code>.protobuf.BInteger int_val = 2;</code>
     */
    public boolean hasIntVal() {
      return intValBuilder_ != null || intVal_ != null;
    }
    /**
     * <code>.protobuf.BInteger int_val = 2;</code>
     */
    public moonbox.message.protobuf.BInteger getIntVal() {
      if (intValBuilder_ == null) {
        return intVal_ == null ? moonbox.message.protobuf.BInteger.getDefaultInstance() : intVal_;
      } else {
        return intValBuilder_.getMessage();
      }
    }
    /**
     * <code>.protobuf.BInteger int_val = 2;</code>
     */
    public Builder setIntVal(moonbox.message.protobuf.BInteger value) {
      if (intValBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        intVal_ = value;
        onChanged();
      } else {
        intValBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.protobuf.BInteger int_val = 2;</code>
     */
    public Builder setIntVal(
        moonbox.message.protobuf.BInteger.Builder builderForValue) {
      if (intValBuilder_ == null) {
        intVal_ = builderForValue.build();
        onChanged();
      } else {
        intValBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.protobuf.BInteger int_val = 2;</code>
     */
    public Builder mergeIntVal(moonbox.message.protobuf.BInteger value) {
      if (intValBuilder_ == null) {
        if (intVal_ != null) {
          intVal_ =
            moonbox.message.protobuf.BInteger.newBuilder(intVal_).mergeFrom(value).buildPartial();
        } else {
          intVal_ = value;
        }
        onChanged();
      } else {
        intValBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.protobuf.BInteger int_val = 2;</code>
     */
    public Builder clearIntVal() {
      if (intValBuilder_ == null) {
        intVal_ = null;
        onChanged();
      } else {
        intVal_ = null;
        intValBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.protobuf.BInteger int_val = 2;</code>
     */
    public moonbox.message.protobuf.BInteger.Builder getIntValBuilder() {
      
      onChanged();
      return getIntValFieldBuilder().getBuilder();
    }
    /**
     * <code>.protobuf.BInteger int_val = 2;</code>
     */
    public moonbox.message.protobuf.BIntegerOrBuilder getIntValOrBuilder() {
      if (intValBuilder_ != null) {
        return intValBuilder_.getMessageOrBuilder();
      } else {
        return intVal_ == null ?
            moonbox.message.protobuf.BInteger.getDefaultInstance() : intVal_;
      }
    }
    /**
     * <code>.protobuf.BInteger int_val = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        moonbox.message.protobuf.BInteger, moonbox.message.protobuf.BInteger.Builder, moonbox.message.protobuf.BIntegerOrBuilder> 
        getIntValFieldBuilder() {
      if (intValBuilder_ == null) {
        intValBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            moonbox.message.protobuf.BInteger, moonbox.message.protobuf.BInteger.Builder, moonbox.message.protobuf.BIntegerOrBuilder>(
                getIntVal(),
                getParentForChildren(),
                isClean());
        intVal_ = null;
      }
      return intValBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protobuf.BDecimal)
  }

  // @@protoc_insertion_point(class_scope:protobuf.BDecimal)
  private static final moonbox.message.protobuf.BDecimal DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new moonbox.message.protobuf.BDecimal();
  }

  public static moonbox.message.protobuf.BDecimal getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BDecimal>
      PARSER = new com.google.protobuf.AbstractParser<BDecimal>() {
    public BDecimal parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BDecimal(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BDecimal> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BDecimal> getParserForType() {
    return PARSER;
  }

  public moonbox.message.protobuf.BDecimal getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

