// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_message.proto

package moonbox.message.protobuf;

public interface OpenSessionInboundOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.OpenSessionInbound)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   */
  java.lang.String getToken();
  /**
   * <code>string token = 1;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>string database = 2;</code>
   */
  java.lang.String getDatabase();
  /**
   * <code>string database = 2;</code>
   */
  com.google.protobuf.ByteString
      getDatabaseBytes();

  /**
   * <code>bool isLocal = 3;</code>
   */
  boolean getIsLocal();
}
