// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_message.proto

package moonbox.message.protobuf;

/**
 * Protobuf type {@code protobuf.ResultData}
 */
public  final class ResultData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protobuf.ResultData)
    ResultDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResultData.newBuilder() to construct.
  private ResultData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResultData() {
    cursor_ = "";
    schema_ = "";
    hasNext_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ResultData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            cursor_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            schema_ = s;
            break;
          }
          case 26: {
            moonbox.message.protobuf.Data.Builder subBuilder = null;
            if (data_ != null) {
              subBuilder = data_.toBuilder();
            }
            data_ = input.readMessage(moonbox.message.protobuf.Data.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(data_);
              data_ = subBuilder.buildPartial();
            }

            break;
          }
          case 32: {

            hasNext_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return moonbox.message.protobuf.ProtoMessageOuterClass.internal_static_protobuf_ResultData_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return moonbox.message.protobuf.ProtoMessageOuterClass.internal_static_protobuf_ResultData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            moonbox.message.protobuf.ResultData.class, moonbox.message.protobuf.ResultData.Builder.class);
  }

  public static final int CURSOR_FIELD_NUMBER = 1;
  private volatile java.lang.Object cursor_;
  /**
   * <code>string cursor = 1;</code>
   */
  public java.lang.String getCursor() {
    java.lang.Object ref = cursor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cursor_ = s;
      return s;
    }
  }
  /**
   * <code>string cursor = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCursorBytes() {
    java.lang.Object ref = cursor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cursor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SCHEMA_FIELD_NUMBER = 2;
  private volatile java.lang.Object schema_;
  /**
   * <code>string schema = 2;</code>
   */
  public java.lang.String getSchema() {
    java.lang.Object ref = schema_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      schema_ = s;
      return s;
    }
  }
  /**
   * <code>string schema = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSchemaBytes() {
    java.lang.Object ref = schema_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      schema_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATA_FIELD_NUMBER = 3;
  private moonbox.message.protobuf.Data data_;
  /**
   * <pre>
   * data Seq[Seq[Any]]
   * </pre>
   *
   * <code>.protobuf.Data data = 3;</code>
   */
  public boolean hasData() {
    return data_ != null;
  }
  /**
   * <pre>
   * data Seq[Seq[Any]]
   * </pre>
   *
   * <code>.protobuf.Data data = 3;</code>
   */
  public moonbox.message.protobuf.Data getData() {
    return data_ == null ? moonbox.message.protobuf.Data.getDefaultInstance() : data_;
  }
  /**
   * <pre>
   * data Seq[Seq[Any]]
   * </pre>
   *
   * <code>.protobuf.Data data = 3;</code>
   */
  public moonbox.message.protobuf.DataOrBuilder getDataOrBuilder() {
    return getData();
  }

  public static final int HAS_NEXT_FIELD_NUMBER = 4;
  private boolean hasNext_;
  /**
   * <code>bool has_next = 4;</code>
   */
  public boolean getHasNext() {
    return hasNext_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCursorBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, cursor_);
    }
    if (!getSchemaBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, schema_);
    }
    if (data_ != null) {
      output.writeMessage(3, getData());
    }
    if (hasNext_ != false) {
      output.writeBool(4, hasNext_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCursorBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, cursor_);
    }
    if (!getSchemaBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, schema_);
    }
    if (data_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getData());
    }
    if (hasNext_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, hasNext_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof moonbox.message.protobuf.ResultData)) {
      return super.equals(obj);
    }
    moonbox.message.protobuf.ResultData other = (moonbox.message.protobuf.ResultData) obj;

    boolean result = true;
    result = result && getCursor()
        .equals(other.getCursor());
    result = result && getSchema()
        .equals(other.getSchema());
    result = result && (hasData() == other.hasData());
    if (hasData()) {
      result = result && getData()
          .equals(other.getData());
    }
    result = result && (getHasNext()
        == other.getHasNext());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CURSOR_FIELD_NUMBER;
    hash = (53 * hash) + getCursor().hashCode();
    hash = (37 * hash) + SCHEMA_FIELD_NUMBER;
    hash = (53 * hash) + getSchema().hashCode();
    if (hasData()) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
    }
    hash = (37 * hash) + HAS_NEXT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHasNext());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static moonbox.message.protobuf.ResultData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static moonbox.message.protobuf.ResultData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static moonbox.message.protobuf.ResultData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static moonbox.message.protobuf.ResultData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static moonbox.message.protobuf.ResultData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static moonbox.message.protobuf.ResultData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static moonbox.message.protobuf.ResultData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static moonbox.message.protobuf.ResultData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static moonbox.message.protobuf.ResultData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static moonbox.message.protobuf.ResultData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static moonbox.message.protobuf.ResultData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static moonbox.message.protobuf.ResultData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(moonbox.message.protobuf.ResultData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protobuf.ResultData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protobuf.ResultData)
      moonbox.message.protobuf.ResultDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return moonbox.message.protobuf.ProtoMessageOuterClass.internal_static_protobuf_ResultData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return moonbox.message.protobuf.ProtoMessageOuterClass.internal_static_protobuf_ResultData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              moonbox.message.protobuf.ResultData.class, moonbox.message.protobuf.ResultData.Builder.class);
    }

    // Construct using moonbox.message.protobuf.ResultData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      cursor_ = "";

      schema_ = "";

      if (dataBuilder_ == null) {
        data_ = null;
      } else {
        data_ = null;
        dataBuilder_ = null;
      }
      hasNext_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return moonbox.message.protobuf.ProtoMessageOuterClass.internal_static_protobuf_ResultData_descriptor;
    }

    public moonbox.message.protobuf.ResultData getDefaultInstanceForType() {
      return moonbox.message.protobuf.ResultData.getDefaultInstance();
    }

    public moonbox.message.protobuf.ResultData build() {
      moonbox.message.protobuf.ResultData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public moonbox.message.protobuf.ResultData buildPartial() {
      moonbox.message.protobuf.ResultData result = new moonbox.message.protobuf.ResultData(this);
      result.cursor_ = cursor_;
      result.schema_ = schema_;
      if (dataBuilder_ == null) {
        result.data_ = data_;
      } else {
        result.data_ = dataBuilder_.build();
      }
      result.hasNext_ = hasNext_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof moonbox.message.protobuf.ResultData) {
        return mergeFrom((moonbox.message.protobuf.ResultData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(moonbox.message.protobuf.ResultData other) {
      if (other == moonbox.message.protobuf.ResultData.getDefaultInstance()) return this;
      if (!other.getCursor().isEmpty()) {
        cursor_ = other.cursor_;
        onChanged();
      }
      if (!other.getSchema().isEmpty()) {
        schema_ = other.schema_;
        onChanged();
      }
      if (other.hasData()) {
        mergeData(other.getData());
      }
      if (other.getHasNext() != false) {
        setHasNext(other.getHasNext());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      moonbox.message.protobuf.ResultData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (moonbox.message.protobuf.ResultData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object cursor_ = "";
    /**
     * <code>string cursor = 1;</code>
     */
    public java.lang.String getCursor() {
      java.lang.Object ref = cursor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cursor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cursor = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCursorBytes() {
      java.lang.Object ref = cursor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cursor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cursor = 1;</code>
     */
    public Builder setCursor(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cursor_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cursor = 1;</code>
     */
    public Builder clearCursor() {
      
      cursor_ = getDefaultInstance().getCursor();
      onChanged();
      return this;
    }
    /**
     * <code>string cursor = 1;</code>
     */
    public Builder setCursorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cursor_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object schema_ = "";
    /**
     * <code>string schema = 2;</code>
     */
    public java.lang.String getSchema() {
      java.lang.Object ref = schema_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        schema_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string schema = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSchemaBytes() {
      java.lang.Object ref = schema_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        schema_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string schema = 2;</code>
     */
    public Builder setSchema(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      schema_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string schema = 2;</code>
     */
    public Builder clearSchema() {
      
      schema_ = getDefaultInstance().getSchema();
      onChanged();
      return this;
    }
    /**
     * <code>string schema = 2;</code>
     */
    public Builder setSchemaBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      schema_ = value;
      onChanged();
      return this;
    }

    private moonbox.message.protobuf.Data data_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        moonbox.message.protobuf.Data, moonbox.message.protobuf.Data.Builder, moonbox.message.protobuf.DataOrBuilder> dataBuilder_;
    /**
     * <pre>
     * data Seq[Seq[Any]]
     * </pre>
     *
     * <code>.protobuf.Data data = 3;</code>
     */
    public boolean hasData() {
      return dataBuilder_ != null || data_ != null;
    }
    /**
     * <pre>
     * data Seq[Seq[Any]]
     * </pre>
     *
     * <code>.protobuf.Data data = 3;</code>
     */
    public moonbox.message.protobuf.Data getData() {
      if (dataBuilder_ == null) {
        return data_ == null ? moonbox.message.protobuf.Data.getDefaultInstance() : data_;
      } else {
        return dataBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * data Seq[Seq[Any]]
     * </pre>
     *
     * <code>.protobuf.Data data = 3;</code>
     */
    public Builder setData(moonbox.message.protobuf.Data value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        dataBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * data Seq[Seq[Any]]
     * </pre>
     *
     * <code>.protobuf.Data data = 3;</code>
     */
    public Builder setData(
        moonbox.message.protobuf.Data.Builder builderForValue) {
      if (dataBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        dataBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * data Seq[Seq[Any]]
     * </pre>
     *
     * <code>.protobuf.Data data = 3;</code>
     */
    public Builder mergeData(moonbox.message.protobuf.Data value) {
      if (dataBuilder_ == null) {
        if (data_ != null) {
          data_ =
            moonbox.message.protobuf.Data.newBuilder(data_).mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        dataBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * data Seq[Seq[Any]]
     * </pre>
     *
     * <code>.protobuf.Data data = 3;</code>
     */
    public Builder clearData() {
      if (dataBuilder_ == null) {
        data_ = null;
        onChanged();
      } else {
        data_ = null;
        dataBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * data Seq[Seq[Any]]
     * </pre>
     *
     * <code>.protobuf.Data data = 3;</code>
     */
    public moonbox.message.protobuf.Data.Builder getDataBuilder() {
      
      onChanged();
      return getDataFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * data Seq[Seq[Any]]
     * </pre>
     *
     * <code>.protobuf.Data data = 3;</code>
     */
    public moonbox.message.protobuf.DataOrBuilder getDataOrBuilder() {
      if (dataBuilder_ != null) {
        return dataBuilder_.getMessageOrBuilder();
      } else {
        return data_ == null ?
            moonbox.message.protobuf.Data.getDefaultInstance() : data_;
      }
    }
    /**
     * <pre>
     * data Seq[Seq[Any]]
     * </pre>
     *
     * <code>.protobuf.Data data = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        moonbox.message.protobuf.Data, moonbox.message.protobuf.Data.Builder, moonbox.message.protobuf.DataOrBuilder> 
        getDataFieldBuilder() {
      if (dataBuilder_ == null) {
        dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            moonbox.message.protobuf.Data, moonbox.message.protobuf.Data.Builder, moonbox.message.protobuf.DataOrBuilder>(
                getData(),
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      return dataBuilder_;
    }

    private boolean hasNext_ ;
    /**
     * <code>bool has_next = 4;</code>
     */
    public boolean getHasNext() {
      return hasNext_;
    }
    /**
     * <code>bool has_next = 4;</code>
     */
    public Builder setHasNext(boolean value) {
      
      hasNext_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool has_next = 4;</code>
     */
    public Builder clearHasNext() {
      
      hasNext_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protobuf.ResultData)
  }

  // @@protoc_insertion_point(class_scope:protobuf.ResultData)
  private static final moonbox.message.protobuf.ResultData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new moonbox.message.protobuf.ResultData();
  }

  public static moonbox.message.protobuf.ResultData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResultData>
      PARSER = new com.google.protobuf.AbstractParser<ResultData>() {
    public ResultData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ResultData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ResultData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResultData> getParserForType() {
    return PARSER;
  }

  public moonbox.message.protobuf.ResultData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

